In [7]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [2]:
import pandas as pd

In [8]:
df = pd.read_parquet("branch.parquet")
print(df.shape)
df.head()

(9000, 9)

,branch_code,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type
0,1000,"89 Commercial Complex, Jodhpur",474005,Jodhpur,Tamil Nadu,18,18.09,161.24,urban
1,1001,"30 Station Area, Bhopal",695037,Bhopal,Telangana,34,17.38,388.79,urban
2,1002,"155 Commercial Complex, Coimbatore",670012,Coimbatore,Telangana,23,10.63,280.17,semi-urban
3,1003,"89 Industrial Area, Raipur",560041,Raipur,Uttar Pradesh,12,22.95,446.31,urban
4,1004,"132 Main Road, Kolkata",492043,Kolkata,Maharashtra,20,13.64,225.46,urban

In [9]:
df1 = pd.read_parquet("accounts.parquet")
print(df1.shape)
df1.head()

(160153, 22)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None

In [10]:
df_final = df1.merge(df, on="branch_code", how="left")
print(df_final.shape)
df_final.sample(5)

(160153, 30)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type
101260,ACCT_126752,active,100,1,2023-05-24,4359,302045.0,3067.37,S,Y,Y,N,0,None,N,2023-07-16,N,2720.99,3098.28,1685.57,None,None,"18 Industrial Area, Kolkata",176058,Kolkata,Assam,11,11.87,314.20,urban
15695,ACCT_019649,active,804,1,2020-06-08,6873,400192.0,NaN,O,N,N,N,0,None,Y,2022-12-13,N,NaN,-134.52,-155.16,None,None,"36 Commercial Complex, Kolkata",120046,Kolkata,Maharashtra,26,13.63,405.45,rural
58895,ACCT_073681,active,247,1,2023-04-08,5080,400210.0,4246.76,S,Y,Y,Y,0,None,Y,2021-05-25,N,4920.34,4839.51,4235.48,None,None,"140 Commercial Complex, Lucknow",411048,Lucknow,Uttarakhand,4,5.35,186.12,urban
37297,ACCT_046577,active,1313,1,2023-12-24,4751,700111.0,5652.47,K,Y,Y,N,0,None,Y,2025-04-08,N,5670.25,6578.50,7071.61,None,None,"171 Main Road, Nagpur",121034,Nagpur,Gujarat,36,20.28,284.21,urban
101725,ACCT_127325,active,193,1,2023-12-13,8340,302047.0,3994.01,K,Y,Y,Y,3,None,Y,2024-06-02,N,3781.73,4568.06,5036.66,None,None,"40 Commercial Complex, Dehradun",570021,Dehradun,Uttar Pradesh,42,15.44,50.53,rural

In [13]:
df3 = pd.read_parquet("accounts-additional.parquet")
print(df3.shape)
df3.head()

(160153, 2)

    account_id scheme_code
0  ACCT_000000       PMJDY
1  ACCT_000002     REGULAR
2  ACCT_000003     REGULAR
3  ACCT_000004       PMJDY
4  ACCT_000005     REGULAR

In [18]:
df3.account_id.nunique()

160153

In [14]:
df4 = pd.read_parquet("customer_account_linkage.parquet")
print(df4.shape)
df4.head()

(160153, 2)

   customer_id   account_id
0  CUST_000000  ACCT_000000
1  CUST_000002  ACCT_000002
2  CUST_000003  ACCT_000003
3  CUST_000004  ACCT_000004
4  CUST_000005  ACCT_000005

In [15]:
df4.customer_id.nunique()

159416

In [17]:
df4.account_id.nunique()

160153

### Merge account columns : -

In [19]:
df_result = df_final.merge(df3, on="account_id", how="left")
print(df_result.shape)
df_result.sample(5)

(160153, 31)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code
118794,ACCT_148650,active,105,1,2023-11-28,6850,452050.0,887.16,S,Y,Y,N,0,None,Y,2024-01-20,N,997.46,821.91,748.36,None,None,"53 Market Street, Bhopal",250045,Bhopal,Gujarat,18,16.02,102.07,urban,REGULAR
118996,ACCT_148897,active,1102,1,2023-09-06,7127,244003.0,-3491.97,K,N,Y,N,0,2025-02-01,Y,2023-11-07,Y,-3502.09,-3364.33,-3432.80,None,None,"181 Main Road, Mumbai",190018,Mumbai,Karnataka,41,11.42,126.84,rural,REGULAR
48905,ACCT_061153,active,200,1,2022-01-22,2733,600070.0,8257.95,K,N,Y,N,0,None,Y,2022-05-14,N,7631.94,8476.47,11664.05,2023-09-11,2023-10-28,"17 Market Street, Shimla",411098,Shimla,Andhra Pradesh,7,16.47,159.78,semi-urban,REGULAR
36349,ACCT_045414,active,100,1,2023-05-31,2351,400035.0,277002.32,S,N,Y,N,0,None,Y,2024-07-30,N,311638.08,264238.39,413293.75,None,None,"23 Station Area, Srinagar",560012,Srinagar,Jammu & Kashmir,26,22.00,480.69,urban,PMJJBY
70687,ACCT_088498,frozen,1102,1,2021-11-28,8992,620023.0,411.92,K,N,Y,Y,0,None,Y,2021-06-02,N,417.51,427.01,613.63,2023-12-25,None,"71 Industrial Area, Panaji",462020,Panaji,Delhi,7,14.89,247.33,urban,REGULAR

In [20]:
df_result_f = df_result.merge(df4, on="account_id", how="left")
print(df_result_f.shape)
df_result_f.sample(5)

(160153, 32)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id
26010,ACCT_032560,active,897,1,2022-08-02,8824,110167.0,16084.11,S,Y,Y,Y,1,None,Y,2024-02-26,N,14320.39,12197.71,14506.14,None,None,"25 Main Road, Jodhpur",282016,Jodhpur,Uttar Pradesh,10,20.13,395.71,rural,REGULAR,CUST_032466
34497,ACCT_043164,active,169,1,2023-04-15,2115,492049.0,6528.61,S,Y,Y,N,0,None,Y,2022-06-13,N,5788.18,5236.66,8966.50,None,None,"91 Market Street, Hyderabad",403017,Hyderabad,Telangana,18,18.59,411.96,urban,REGULAR,CUST_043043
92109,ACCT_115360,active,804,1,2025-03-09,4700,515035.0,3561.22,O,Y,N,N,0,2025-04-25,Y,2025-03-13,Y,3413.37,4111.83,4510.82,None,None,"157 Station Area, Bhopal",211038,Bhopal,Bihar,9,21.05,108.23,rural,REGULAR,CUST_115017
25963,ACCT_032503,active,200,1,2022-11-03,6997,560130.0,61137.73,K,N,Y,N,0,None,Y,2024-09-16,N,50084.66,59839.84,69586.55,None,None,"157 Market Street, Kolkata",421010,Kolkata,Gujarat,36,18.28,247.03,urban,PMJDY,CUST_032409
58336,ACCT_072986,active,200,1,2023-07-26,7636,NaN,218.44,K,N,Y,N,0,None,Y,2023-05-16,N,182.42,274.77,283.65,2025-03-19,2025-06-03,"167 Station Area, Raipur",847009,Raipur,Andhra Pradesh,33,8.45,122.01,semi-urban,REGULAR,CUST_072773

In [24]:
df_result_f.to_parquet("f_a.parquet", engine="pyarrow", compression="snappy")

### **Customer id merge**

In [25]:
df5 = pd.read_parquet("f_a.parquet")
print(df5.shape)
df5.head()

(160153, 32)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005

In [27]:
df7= pd.read_parquet("customers.parquet")
print(df7.shape)    
df7.head()

(159416, 14)

,customer_id,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin
0,CUST_000000,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008
1,CUST_000002,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074
2,CUST_000003,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033
3,CUST_000004,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035
4,CUST_000005,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024

In [28]:
df8 = pd.read_parquet("demographics.parquet")
print(df8.shape)    
df8.head()

(159416, 9)

,customer_id,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag
0,CUST_000000,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N
1,CUST_000002,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N
2,CUST_000003,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N
3,CUST_000004,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N
4,CUST_000005,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N

In [30]:
df_result = df7.merge(df8, on="customer_id", how="left")
print(df_result.shape)
df_result.sample(5)

(159416, 22)

,customer_id,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag
103844,CUST_129803,1976-03-04,1996-03-29,Y,None,N,N,Y,N,N,N,N,530020,530020,Amit Banerjee,M,2018-11-17,"36 Nehru Road, Nagpur",91-7817743276,2024-06-06,N,N
135697,CUST_169549,1989-02-19,2007-02-17,N,Y,N,N,N,Y,N,Y,N,625113,625113,Advik Pillai,M,2018-08-24,"27 Temple Street, Hyderabad",91-8431002972,None,Y,N
61810,CUST_077273,1990-01-17,2023-03-30,Y,N,N,N,N,N,N,N,N,400005,400005,Rajesh Mishra,M,2024-09-02,"392 MG Road, New Delhi",91-9568438875,2022-10-18,N,N
82538,CUST_103267,1995-07-17,2015-09-06,Y,N,N,N,N,N,N,N,N,248041,248041,Arjun Menon,M,2020-01-31,"371 Civil Lines, Kochi",91-7928509275,2021-03-20,N,N
95885,CUST_119937,1995-03-18,2020-06-05,Y,Y,N,N,N,N,N,N,N,614033,614033,Advaith Mukherjee,M,2024-01-05,"349 Station Road, Varanasi",91-8544025127,2020-12-16,N,N

In [31]:
df9 = pd.read_parquet("product_details.parquet")
print(df9.shape)    
df9.head()

(159416, 11)

,customer_id,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,CUST_000000,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,CUST_000002,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,CUST_000003,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,CUST_000004,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,CUST_000005,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0

In [32]:
df_final = df_result.merge(df9, on="customer_id", how="left")
print(df_final.shape)
df_final.head()

(159416, 32)

,customer_id,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,CUST_000000,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,CUST_000002,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,CUST_000003,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,CUST_000004,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,CUST_000005,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0

In [33]:
df_final.to_parquet("f_c.parquet", engine="pyarrow", compression="snappy")

In [34]:
op = pd.read_parquet("f_c.parquet")
print(op.shape)     
op.head()

(159416, 32)

,customer_id,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,CUST_000000,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,CUST_000002,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,CUST_000003,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,CUST_000004,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,CUST_000005,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0