In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [84]:
import pandas as pd

In [2]:
df_train = pd.read_parquet("train_labels.parquet")
print(df_train.shape)
df_train.head(4)

(96091, 5)

    account_id  is_mule mule_flag_date alert_reason  flagged_by_branch
0  ACCT_000000        0           None         None                NaN
1  ACCT_000002        0           None         None                NaN
2  ACCT_000003        0           None         None                NaN
3  ACCT_000004        0           None         None                NaN

In [5]:
df_test = pd.read_parquet("test_accounts.parquet")
print(df_test.shape)
# df_test.head(4)

(64062, 1)

In [8]:
df_final = pd.read_parquet("f_t2.parquet")
print(df_final.shape)

(160153, 147)

In [9]:
matched1 = df_final["account_id"].isin(df_test["account_id"]).sum()

print(matched1)

64062

In [87]:
df_acc = pd.read_parquet("f_a.parquet")
print(df_acc.shape)
df_train.head()

(160153, 32)

    account_id  is_mule mule_flag_date alert_reason  flagged_by_branch
0  ACCT_000000        0           None         None                NaN
1  ACCT_000002        0           None         None                NaN
2  ACCT_000003        0           None         None                NaN
3  ACCT_000004        0           None         None                NaN
4  ACCT_000008        0           None         None                NaN

**Matching accounts in between train and accounts : -**

In [88]:
matched = df_train["account_id"].isin(df_acc["account_id"]).sum()
print(matched)

96091

**Matching accounts in between train and test : -**

In [89]:
matched1 = df_train["account_id"].isin(df_test["account_id"]).sum()

print(matched1)

0

In [90]:
matched1 = df_acc["account_id"].isin(df_test["account_id"]).sum()

print(matched1)

64062

In [91]:
df = pd.read_parquet("f_a.parquet")
print(df.shape)
df.head()

(160153, 32)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005

In [92]:
print(df.customer_id.nunique())
print(df.account_id.nunique())

159416
160153

In [93]:
df["multi_customer"] = (
    df.groupby("account_id")["customer_id"]
    .transform("nunique") > 1
).astype(int)
print(df.shape)
df.head()

(160153, 33)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004,0
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005,0

In [94]:
matched1 = df["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

96091

In [95]:
df_c = pd.read_parquet("f_c.parquet")
print(df_c.shape)
df_c.head()

(159416, 32)

,customer_id,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,CUST_000000,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,CUST_000002,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,CUST_000003,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,CUST_000004,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,CUST_000005,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0

### final merger: -

In [96]:
df_merged = df.merge(
    df_c,
    on="customer_id",
    how="left"
)
print(df_merged.shape)
df_merged.head()

(160153, 64)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004,0,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005,0,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0

In [97]:
matched1 = df_merged["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

96091

In [98]:
# df_merged.to_parquet("f_ac.parquet", engine="pyarrow", compression="snappy")

In [99]:
df = pd.read_parquet("f_ac.parquet", engine="pyarrow")
df.sample(6)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
159515,ACCT_199388,active,804,1,2018-04-30,1933,600029.0,-126862.22,O,N,N,N,0,None,Y,2023-03-30,N,-112619.59,-124076.07,-117459.53,None,None,"159 Main Road, Mumbai",403050,Mumbai,Gujarat,17,7.21,488.53,rural,REGULAR,CUST_198791,0,1968-04-20,2014-06-24,N,Y,N,N,Y,Y,N,N,N,600029,600029,Advaith Mukherjee,M,2016-04-25,"68 Nehru Road, Jaipur",91-8701920975,None,N,N,NaN,0,NaN,0,-23797.52,1,0.0,0,0.00,0
10064,ACCT_012632,active,113,1,2023-07-07,8950,395031.0,35123.03,S,N,Y,N,0,2025-05-07,Y,2022-07-10,N,39507.43,37024.15,21562.59,None,None,"36 Commercial Complex, Ahmedabad",580035,Ahmedabad,Jammu & Kashmir,31,12.92,78.17,urban,PMSBY,CUST_012597,0,1962-04-16,2017-08-02,Y,None,N,N,Y,Y,N,Y,N,395031,395031,Nisha Shah,F,2016-08-12,"357 Sector 46, Visakhapatnam",91-6265185194,2025-05-26,Y,N,NaN,0,-173905.91,2,0.00,0,0.0,0,35123.03,1
37163,ACCT_046422,active,169,1,2023-11-28,6882,143010.0,81890.54,S,N,Y,N,0,None,Y,2021-12-17,N,87536.98,92726.06,105815.76,None,None,"45 Industrial Area, Dehradun",120046,Dehradun,Jammu & Kashmir,49,24.01,338.14,urban,REGULAR,CUST_046290,0,1960-03-09,1999-08-16,Y,None,N,N,Y,Y,N,N,N,143010,143010,Pranav Reddy,M,2023-09-05,"169 Station Road, Panaji",91-7396492961,None,Y,N,NaN,0,NaN,0,0.00,0,0.0,0,81890.54,1
99669,ACCT_124788,active,161,1,2023-11-12,4603,700139.0,NaN,S,Y,Y,Y,3,None,Y,2024-10-20,N,NaN,1795.97,956.07,None,None,"129 Main Road, Thiruvananthapuram",400181,Thiruvananthapuram,Madhya Pradesh,14,14.69,410.45,semi-urban,REGULAR,CUST_124418,0,1970-03-15,2001-03-29,Y,Y,N,Y,Y,Y,N,N,N,302070,302070,Advaith Nair,M,2022-06-01,"289 Park Avenue, Kolkata",91-8770868589,2022-08-17,N,N,NaN,0,NaN,0,0.00,0,0.0,0,0.00,1
37691,ACCT_047071,active,106,1,2023-07-09,5078,431054.0,4535.34,S,Y,Y,Y,2,None,Y,2025-03-05,Y,5311.66,4937.67,2623.05,None,None,"110 Commercial Complex, Pune",560095,Pune,Tamil Nadu,16,7.39,322.51,urban,REGULAR,CUST_046939,0,1981-05-02,1997-01-30,Y,Y,Y,N,N,Y,N,N,N,244020,625100,Krishna Reddy,M,2022-06-23,"421 Nehru Road, Bangalore",91-7210208694,2021-11-23,N,N,NaN,0,NaN,0,0.00,0,0.0,0,4535.34,1
157758,ACCT_197210,active,169,1,2024-06-25,1533,NaN,NaN,S,N,Y,N,0,None,Y,2022-07-08,N,NaN,46718.56,54800.29,None,None,"63 Market Street, Dehradun",110193,Dehradun,Himachal Pradesh,26,6.36,180.20,urban,REGULAR,CUST_196618,0,1998-05-06,1995-01-07,Y,Y,N,N,N,Y,N,N,Y,700186,700186,Tanvi Jain,F,2023-08-24,"180 Temple Street, Bangalore",91-6763817417,2023-05-12,N,N,NaN,0,NaN,0,0.00,0,0.0,0,0.00,1

In [100]:
matched1 = df["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

96091

In [101]:
df_txn = pd.read_parquet("transaction_final.parquet")
print(df_txn.shape)
df_txn.head()

(159776, 83)

,account_id,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day
0,ACCT_002631,8227,58,9384,1785,2557,5905,35,UPC,3057,UPD,END,3,17,3,16,SCW,7399,2.104429e+08,25579.548961,35214000.00,-2270044.26,407942.578626,1000.0,81534279.29,1.289087e+08,4418871.15,35214000.00,0.632496,0.447308,0.552692,981.771699,459.0,17,6,138,673,87.521277,3.664588,587.642857,2056.750000,0.056521,0.926462,323.0,20,0.997569,20,19,3.930540,12,0.084566,18.532609,20,0.760901,2649,0.321989,2649,15.284119,1,2825,0.343382,2825,1.0,0.000354,27,0.003282,"CDM,CRM",-1.685111e+07,-56185203.85,-1.667784e+07,-1.699135e+07,5010646.55,0.0,0.0,0.0,0.962805,0.036830,0.000365,0.0,2.0,8.0,31.0,56.0
1,ACCT_002643,1958,52,9384,399,2769,9355,32,UPC,720,UPC,UPC,1,2,1,2,SCW,4816,5.808451e+07,29665.226404,14496908.97,-127127.28,365480.588591,900.0,18665007.33,3.941951e+07,4716000.00,14496908.97,0.473497,0.471399,0.528601,32101.411344,16870.0,3,3,10,30,2.689560,0.112193,18.826923,81.583333,0.050562,0.929520,10.0,5,0.997446,5,4,1.062225,3,0.007342,2.140244,5,0.203459,681,0.347804,681,15.284570,1,662,0.338100,662,1.0,0.001511,6,0.003064,"CRM,CDM",-1.853798e+07,-24756920.74,-1.812036e+07,-1.891041e+07,593784.16,0.0,0.0,0.0,0.957610,0.030644,0.011747,0.0,1.0,2.0,2.0,5.0
2,ACCT_002653,1289,52,9384,292,2921,9384,32,UPD,483,UPC,UPD,1,1,1,1,ASD,7523,2.815076e+07,21839.222327,3312531.54,-2500.00,142942.038372,800.0,14683386.15,1.346737e+07,3312531.54,2421381.76,1.090293,0.494957,0.505043,122284.975932,82788.0,3,2,5,13,0.706689,0.029462,4.938697,21.483333,0.055081,0.933282,1.0,8,0.993794,8,7,1.009427,2,0.001440,1.339560,4,0.032619,397,0.307991,397,1983.674444,1,408,0.316524,408,1.0,0.002451,3,0.002327,CDM,2.577059e+06,-950616.61,2.565631e+06,2.588259e+06,6897184.10,0.0,0.0,0.0,0.920869,0.032583,0.046548,0.0,1.0,2.0,1.0,3.0
3,ACCT_002660,1845,53,9384,396,2017,2944,33,UPC,682,UPD,ATW,1,2,1,2,IAD,5944,4.405927e+07,23880.365599,9148897.93,-52000.00,230541.369695,1000.0,16494792.15,2.756448e+07,1022119.47,9148897.93,0.598407,0.462331,0.537669,29905.380694,16905.0,4,2,9,31,2.887324,0.120431,20.054348,83.863636,0.061247,0.918699,10.0,21,0.988618,21,20,1.086391,4,0.002465,2.911715,8,0.049520,590,0.319783,590,15.166883,1,624,0.338211,624,1.0,0.001603,10,0.005420,"CDM,CRM",-5.761094e+06,-13536755.77,-5.808792e+06,-5.720080e+06,137193.14,0.0,0.0,0.0,0.949051,0.039566,0.011382,0.0,1.0,3.0,2.0,5.0
4,ACCT_002667,2777,56,9384,626,2017,5905,33,UPC,1046,UPC,UPC,1,2,1,2,CTC,5812,8.148030e+07,29341.123554,12829813.10,-36461.27,327845.023800,1000.0,36753995.17,4.472630e+07,9862500.00,12829813.10,0.821753,0.473533,0.526467,26114.803314,13702.5,4,2,11,39,3.305952,0.137899,23.141667,99.178571,0.055456,0.922578,15.0,28,0.989917,28,27,1.106145,3,0.000898,3.341837,9,0.038539,924,0.332733,924,15.118791,1,961,0.346057,961,1.0,0.001041,7,0.002521,"CRM,CDM",-8.097419e+06,-19051646.09,-8.001798e+06,-8.183426e+06,907379.30,0.0,0.0,0.0,0.957868,0.032409,0.009723,0.0,1.0,2.0,2.0,6.0

In [102]:
matched1 = df_txn["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

95880

In [103]:
df_acc = pd.read_parquet("f_ac.parquet")
print(df_acc.shape)
df_acc.head()

(160153, 64)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004,0,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005,0,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0

In [104]:
df_merged = df_acc.merge(
    df_txn,
    on="account_id",
    how="left"
)
print(df_merged.shape)
df_merged.sample(5)

(160153, 146)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day
138600,ACCT_173314,active,100,1,2021-06-08,7564,700113.0,6056.89,S,N,Y,Y,3,None,Y,2022-11-30,N,5823.39,5440.51,4484.46,None,None,"53 Industrial Area, Chandigarh",625071,Chandigarh,Madhya Pradesh,18,18.81,321.72,urban,REGULAR,CUST_172798,0,1958-07-24,2013-03-22,Y,N,N,N,N,N,N,N,N,700113,700113,Deepak Gupta,M,2019-06-17,"454 Station Road, Ahmedabad",91-8335179824,2023-01-29,N,N,NaN,0,NaN,0,0.00,0,0.0,0,6056.89,1,4781.0,58.0,9384.0,1005.0,5905.0,2955.0,35.0,UPC,1823.0,CHD,UPD,1.0,2.0,1.0,2.0,IAD,4816.0,1.118154e+08,23387.460458,7769012.44,-135000.00,1.802511e+05,1000.0,38067742.63,73747705.82,2074600.00,7769012.44,0.516189,0.457645,0.542355,26768.362552,14463.5,4.0,3.0,10.0,34.0,3.226046,0.134509,22.551887,97.571429,0.054800,0.924702,23.0,6.0,0.998745,6.0,5.0,1.079733,3.0,0.008981,2.524910,6.0,0.203359,1464.0,0.306212,1464.0,15.127406,1.0,1630.0,0.340933,1630.0,1.0,0.000613,14.0,0.002928,"CRM,CDM",-1.836479e+07,-36421231.90,-1.818344e+07,-1.851781e+07,2511813.36,0.0,0.0,0.0,0.957959,0.032002,0.010040,0.000000,1.0,3.0,2.0,6.0
60928,ACCT_076246,active,247,1,2023-02-22,5213,400100.0,77565.35,S,N,Y,N,0,None,N,2024-08-27,N,64080.02,70444.99,45241.94,None,None,"27 Market Street, Hyderabad",121034,Hyderabad,Telangana,22,5.21,431.67,rural,REGULAR,CUST_076025,0,1980-04-25,2021-08-31,Y,None,N,N,N,Y,N,N,N,400100,400100,Ritvik Mehta,M,2023-12-26,"229 Park Avenue, Kolkata",91-9189604059,None,Y,N,NaN,0,NaN,0,0.00,0,0.0,0,77565.35,1,1433.0,50.0,9384.0,297.0,5905.0,5905.0,33.0,UPC,549.0,UPD,UPD,1.0,1.0,1.0,2.0,IFD,8999.0,3.663948e+07,25568.375897,2646591.91,-83000.00,1.403931e+05,1000.0,13952221.88,22687260.78,1656283.61,2646591.91,0.614980,0.470342,0.529658,51707.701117,34839.5,3.0,2.0,7.0,20.0,1.670163,0.069665,11.650407,49.413793,0.059316,0.923238,6.0,10.0,0.993022,10.0,9.0,1.051622,3.0,0.002581,1.902798,6.0,0.059177,583.0,0.406839,583.0,15.246397,1.0,507.0,0.353803,507.0,1.0,0.001972,4.0,0.002791,"CRM,CDM",-3.917889e+06,-10579599.94,-3.901867e+06,-3.932117e+06,743191.94,0.0,0.0,0.0,0.949058,0.031403,0.019539,0.000000,1.0,2.0,1.0,5.0
40090,ACCT_050076,active,1045,1,2022-09-06,7182,735027.0,3789.14,O,N,N,N,0,None,Y,2025-05-05,Y,4211.79,2724.11,3916.37,None,None,"145 Commercial Complex, Vijayawada",302052,Vijayawada,Tamil Nadu,14,7.82,483.99,rural,REGULAR,CUST_049937,0,1996-02-07,1998-09-15,N,Y,N,Y,N,N,N,N,N,176041,176041,Arnav Das,M,2019-02-11,"468 Temple Street, Hyderabad",91-7770689142,None,N,N,NaN,0,NaN,0,-68439.28,1,0.0,0,0.00,0,2501.0,55.0,9384.0,522.0,5905.0,9355.0,33.0,UPC,898.0,UPD,UPC,1.0,2.0,1.0,2.0,ASD,5941.0,6.645570e+07,26571.651152,10030900.00,-57000.00,2.714659e+05,1000.0,29802913.99,36652785.54,4992000.00,10030900.00,0.813115,0.454218,0.545782,35452.329600,19772.5,4.0,2.0,10.0,28.0,2.435248,0.101580,17.013605,73.558824,0.048780,0.933227,7.0,4.0,0.998401,3.0,4.0,1.055244,3.0,0.011545,1.842904,4.0,0.221175,771.0,0.308277,771.0,1366.222077,1.0,880.0,0.351859,880.0,1.0,0.001136,4.0,0.001599,"CDM,CRM",-6.674439e+06,-15242281.66,-6.434835e+06,-6.873845e+06,2536672.18,0.0,0.0,0.0,0.949620,0.037185,0.000000,0.013195,1.0,3.0,2.0,7.0
33066,ACCT_041387,active,100,1,2023-09-11,5272,248014.0,710096.27,S,N,Y,N,0,2025-04-30,N,2021-11-06,N,778939.51,765762.29,567103.40,None,None,"114 Industrial Area, New Delhi",473030,New Delhi,Karnataka,49,6.26,448.01,rural,REGULAR,CUST_041268,0,1986-04-13,2001-02-03,Y,Y,N,Y,N,Y,N,N,N,248014,248014,Rahul Rao,M,2021-04-05,"335 Gandhi Nagar, Dehradun",91-8857349273,2024-06-09,N,N,NaN,0,NaN,0,0.00,0,0.0,0,710096.27,1,1039.0,47.0,9384.0,213.0,5905.0,2921.0,34.0,UPC,409.0,UPD,IPM,1.0,1.0,1.0,2.0,SID,9211.0,8.183424e+07,78762.506189,52999313.54,-265563.66,1.654287e+06,1000.0,11523068.65,70311175.28,1961500.00,52999313.54,0.163887,0.479307,0.520693,54620.857418,35994.5,3.0,2.0,7.0,20.0,1.581431,0.065964,11.053191,47.227273,0.050048,0.937440,4.0,17.0,0.983638,17.0,16.0,1.051829,3.0,0.001863,1.933464,6.0,0.030775,325.0,0.312801,325.0,14.624406,1.0,354.0,0.340712,354.0,1.0,0.002825,2.0,0.001925,CDM,-1.203216e+07,-59825103.58,-1.155401e+07,-1.247230e+07,1588586.77,0.0,0.0,0.0,0.950914,0.028874,0.020212,0.000000,1.0,2.0,1.0,4.0
1125,ACCT_001404,active,169,1,2023-11-29,6577,122036.0,127533.36,S,Y,Y,N,0,2025-06-04,Y,2021-06-26,N,149525.04,117258.38,146605.92,None,None,"91 Main Road, Vijayawada",500058,Vijayawada,Maharashtra,25,14.66,316.16,semi-urban,REGULAR,CUST_001398,0,1946-07-21,2013-03-04,N,Y,N,Y,Y,N,N,N,N,793039,793039,Advik Rajput,M,2017-07-25,"438 MG Road, Pune",91-8608349144,2023-02-19,N,N,NaN,0,NaN,0,0.00,0,0.0,0,127533.36,1,1009.0,44.0,9384.0,224.0,9355.0,9384.0,30.0,UPD,379.0,UPD,UPC,1.0,1.0,1.0,2.0,ASD,5311.0,1.966698e+07,19491.556036,2943892.09,-6000.00,1.154027e+05,1000.0,9057395.02,10609585.02,1261700.00,2943892.09,0.853699,0.471754,0.528246,49473.953373,32118.0,3.0,3.0,11.0,23.0,1.745675,0.072831,12.156627,50.450000,0.036670,0.944500,1.0,13.0,0.987116,13.0,12.0,1.068230,3.0,0.003731,2.000000,6.0,0.053271,257.0,0.254708,257.0,1516.163942,1.0,349.0,0.345887,349.0,1.0,0.002865,3.0,0.002973,"CDM,CRM",9.817717e+05,-2711872.89,8.507634e+05,1.098770e+06,2523194.43,0.0,0.0,0.0,0.956392,0.024777,0.018831,0.000000,1.0,2.0,1.0,4.0

In [105]:
matched1 = df_merged["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

96091

In [106]:
df_merged.to_parquet("f_act2.parquet", engine="pyarrow", compression="snappy")

In [107]:
matched1 = df_acc["account_id"].isin(df_txn["account_id"]).sum()

print(matched1)

159776

In [108]:
matched2 = df_acc["account_id"].isin(df_test["account_id"]).sum()

print(matched2)

64062

In [113]:
df = pd.read_parquet("f_act2.parquet", engine="pyarrow")
print(df.shape)
df.head()

(160153, 146)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004,0,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005,0,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
df1 = pd.read_parquet("train_labels.parquet", engine="pyarrow")
print(df1.shape)
df1.head()

(96091, 5)

    account_id  is_mule mule_flag_date alert_reason  flagged_by_branch
0  ACCT_000000        0           None         None                NaN
1  ACCT_000002        0           None         None                NaN
2  ACCT_000003        0           None         None                NaN
3  ACCT_000004        0           None         None                NaN
4  ACCT_000008        0           None         None                NaN

In [111]:
matched1 = df["account_id"].isin(df1["account_id"]).sum()

print(matched1)

96091

In [112]:
df1.is_mule.value_counts()

is_mule
0    93408
1     2683
Name: count, dtype: int64

In [115]:
# Merge the is_mule column
df_main = df.merge(
    df1[['account_id', 'is_mule']],
    on='account_id',
    how='left'
)

# Replace NaN (no match) with -1
df_main['is_mule'] = df_main['is_mule'].fillna(-1).astype(int)
print(df_main.shape)
df_main.head()

(160153, 147)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,ACCT_000004,active,191,1,2017-11-25,3285,400035.0,555715.54,K,Y,Y,N,0,None,Y,2023-10-29,N,647193.23,509836.62,699191.21,None,None,"69 Industrial Area, Srinagar",282004,Srinagar,Odisha,21,5.64,478.34,urban,PMJDY,CUST_000004,0,1971-11-06,2006-04-05,N,None,Y,N,N,N,N,Y,N,400035,400035,Aarav Chatterjee,M,2021-09-17,"430 Park Avenue, Bhubaneswar",91-6609970752,None,N,N,NaN,0,-125254.73,1,0.00,0,555715.54,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,ACCT_000005,active,200,1,2019-01-03,2081,160035.0,16380.55,K,N,Y,N,0,None,Y,2021-12-07,N,15878.60,13651.60,21249.07,None,None,"20 Station Area, Kolkata",400098,Kolkata,Maharashtra,37,21.98,372.88,urban,REGULAR,CUST_000005,0,1998-03-26,2003-02-09,Y,Y,N,Y,Y,N,N,Y,N,613024,613024,Divya Deshpande,F,2023-10-06,"259 Nehru Road, Ranchi",91-6525111842,None,N,N,NaN,0,-15874.35,2,0.00,0,16380.55,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1

In [116]:
matched1 = df_main["account_id"].isin(df_train["account_id"]).sum()

print(matched1)

96091

In [117]:
df_main.to_parquet("f_t2.parquet", engine="pyarrow", compression="snappy")

In [118]:
df_main.is_mule.value_counts()

is_mule
 0    93408
-1    64062
 1     2683
Name: count, dtype: int64

In [82]:
df_acc = pd.read_parquet("f_t.parquet")
print(df_acc.shape)
df_acc.head()

(159776, 147)

,account_id,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_x,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance_y,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,is_mule
0,ACCT_002631,8227,58,9384,1785,2557,5905,35,UPC,3057,UPD,END,3,17,3,16,SCW,7399,2.104429e+08,25579.548961,35214000.00,-2270044.26,407942.578626,1000.0,81534279.29,1.289087e+08,4418871.15,35214000.00,0.632496,0.447308,0.552692,981.771699,459.0,17,6,138,673,87.521277,3.664588,587.642857,2056.750000,0.056521,0.926462,323.0,20,0.997569,20,19,3.930540,12,0.084566,18.532609,20,0.760901,2649,0.321989,2649,15.284119,1,2825,0.343382,2825,1.0,0.000354,27,0.003282,"CDM,CRM",-1.685111e+07,-56185203.85,-1.667784e+07,-1.699135e+07,5010646.55,0.0,0.0,0.0,0.962805,0.036830,0.000365,0.0,2.0,8.0,31.0,56.0,active,193,1,2025-03-27,5587,421012.0,NaN,K,Y,Y,N,0,None,Y,2024-03-23,N,NaN,-13088.07,-5878.88,None,None,"192 Market Street, Raipur",625011,Raipur,Uttarakhand,24,11.98,448.82,urban,REGULAR,CUST_002620,0,1997-07-11,1996-12-14,N,None,N,N,Y,N,N,N,Y,421012,421012,Vihaan Patil,M,2024-10-29,"33 Gandhi Nagar, New Delhi",91-9422464827,None,N,N,-137400.62,2,NaN,0,0.0,0,0.0,1,0.00,0,-1
1,ACCT_002643,1958,52,9384,399,2769,9355,32,UPC,720,UPC,UPC,1,2,1,2,SCW,4816,5.808451e+07,29665.226404,14496908.97,-127127.28,365480.588591,900.0,18665007.33,3.941951e+07,4716000.00,14496908.97,0.473497,0.471399,0.528601,32101.411344,16870.0,3,3,10,30,2.689560,0.112193,18.826923,81.583333,0.050562,0.929520,10.0,5,0.997446,5,4,1.062225,3,0.007342,2.140244,5,0.203459,681,0.347804,681,15.284570,1,662,0.338100,662,1.0,0.001511,6,0.003064,"CRM,CDM",-1.853798e+07,-24756920.74,-1.812036e+07,-1.891041e+07,593784.16,0.0,0.0,0.0,0.957610,0.030644,0.011747,0.0,1.0,2.0,2.0,5.0,active,169,1,2023-07-03,4698,503031.0,18559.42,S,Y,Y,Y,2,None,Y,2022-09-13,Y,19255.20,16728.54,25621.43,None,None,"128 Commercial Complex, Jodhpur",221049,Jodhpur,Andhra Pradesh,48,15.88,248.83,semi-urban,REGULAR,CUST_002632,0,2001-08-19,2011-10-16,Y,Y,N,N,Y,Y,N,N,N,503031,503031,Shreya Rajput,F,2018-04-24,"329 Park Avenue, Vijayawada",91-7364006246,2023-01-19,N,N,NaN,0,NaN,0,0.0,0,0.0,0,18559.42,1,0
2,ACCT_002653,1289,52,9384,292,2921,9384,32,UPD,483,UPC,UPD,1,1,1,1,ASD,7523,2.815076e+07,21839.222327,3312531.54,-2500.00,142942.038372,800.0,14683386.15,1.346737e+07,3312531.54,2421381.76,1.090293,0.494957,0.505043,122284.975932,82788.0,3,2,5,13,0.706689,0.029462,4.938697,21.483333,0.055081,0.933282,1.0,8,0.993794,8,7,1.009427,2,0.001440,1.339560,4,0.032619,397,0.307991,397,1983.674444,1,408,0.316524,408,1.0,0.002451,3,0.002327,CDM,2.577059e+06,-950616.61,2.565631e+06,2.588259e+06,6897184.10,0.0,0.0,0.0,0.920869,0.032583,0.046548,0.0,1.0,2.0,1.0,3.0,active,100,1,2016-05-24,2742,560186.0,-309.27,S,N,Y,N,0,None,Y,2025-04-05,N,-332.88,-303.21,-211.79,None,None,"107 Industrial Area, Visakhapatnam",670039,Visakhapatnam,West Bengal,20,17.03,109.47,rural,REGULAR,CUST_002642,0,1957-08-04,1997-10-24,Y,None,N,N,Y,Y,N,N,N,160068,160068,Dhruv Nair,M,2024-11-20,"67 Gandhi Nagar, Raipur",91-6615296336,2023-03-07,N,N,NaN,0,NaN,0,0.0,0,0.0,0,-309.27,1,0
3,ACCT_002660,1845,53,9384,396,2017,2944,33,UPC,682,UPD,ATW,1,2,1,2,IAD,5944,4.405927e+07,23880.365599,9148897.93,-52000.00,230541.369695,1000.0,16494792.15,2.756448e+07,1022119.47,9148897.93,0.598407,0.462331,0.537669,29905.380694,16905.0,4,2,9,31,2.887324,0.120431,20.054348,83.863636,0.061247,0.918699,10.0,21,0.988618,21,20,1.086391,4,0.002465,2.911715,8,0.049520,590,0.319783,590,15.166883,1,624,0.338211,624,1.0,0.001603,10,0.005420,"CDM,CRM",-5.761094e+06,-13536755.77,-5.808792e+06,-5.720080e+06,137193.14,0.0,0.0,0.0,0.949051,0.039566,0.011382,0.0,1.0,3.0,2.0,5.0,active,193,1,2023-09-29,3146,490017.0,0.00,K,Y,Y,N,0,None,Y,2023-08-29,N,0.00,0.00,0.00,None,None,"143 Commercial Complex, Srinagar",411035,Srinagar,Haryana,25,13.61,455.82,semi-urban,PMJDY,CUST_002649,0,1965-07-04,2011-01-22,Y,Y,N,N,Y,N,N,N,N,490017,490017,Aditya Srivastava,M,2019-07-07,"493 Temple Street, Bhopal",91-7387681212,2025-03-13,N,N,NaN,0,NaN,0,0.0,0,0.0,1,0.00,0,0
4,ACCT_002667,2777,56,9384,626,2017,5905,33,UPC,1046,UPC,UPC,1,2,1,2,CTC,5812,8.148030e+07,29341.123554,12829813.10,-36461.27,327845.023800,1000.0,36753995.17,4.472630e+07,9862500.00,12829813.10,0.821753,0.473533,0.526467,26114.803314,13702.5,4,2,11,39,3.305952,0.137899,23.141667,99.178571,0.055456,0.922578,15.0,28,0.989917,28,27,1.106145,3,0.000898,3.341837,9,0.038539,924,0.332733,924,15.118791,1,961,0.346057,961,1.0,0.001041,7,0.002521,"CRM,CDM",-8.097419e+06,-19051646.09,-8.001798e+06,-8.183426e+06,907379.30,0.0,0.0,0.0,0.957868,0.032409,0.009723,0.0,1.0,2.0,2.0,6.0,active,169,1,2023-03-12,6733,743001.0,356474.68,S,Y,Y,Y,2,2025-04-23,N,2024-01-12,Y,361014.00,318532.73,306547.64,None,None,"107 Main Road, Visakhapatnam",400109,Visakhapatnam,Punjab,31,14.02,176.57,semi-urban,REGULAR,CUST_002656,0,1948-08-12,2011-03-07,Y,Y,N,N,N,N,N,Y,N,743001,302047,Anirudh Chauhan,M,2022-12-14,"299 Civil Lines, New Delhi",91-9512607604,2022-06-19,N,N,-481501.08,1,-12554.04,1,0.0,0,0.0,0,356474.68,1,0

In [33]:
df_train = pd.read_parquet("train_labels.parquet")
print(df_train.shape)   
df_train.head()

(96091, 5)

    account_id  is_mule mule_flag_date alert_reason  flagged_by_branch
0  ACCT_000000        0           None         None                NaN
1  ACCT_000002        0           None         None                NaN
2  ACCT_000003        0           None         None                NaN
3  ACCT_000004        0           None         None                NaN
4  ACCT_000008        0           None         None                NaN

In [34]:
matched1 = df_acc["account_id"].isin(df_test["account_id"]).sum()

print(matched1)

64062