### **Preprocessing: -**

In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_colwidth', None)

In [140]:
df_acc = pd.read_parquet('accounts.parquet')
print(df_acc.shape)

(160153, 22)

In [141]:
df_t = pd.read_parquet("account_age2.parquet")
print(df_t.shape)
df_t.sample(3)

(160153, 5)

,account_id,account_opening_date,last_transaction_date,days_since_account_open,account_open_issue_flag
65077,ACCT_157435,2023-03-05,2025-06-28,846.0,0
134820,ACCT_095514,2023-06-10,2024-01-05,209.0,0
142375,ACCT_129855,2017-03-21,2023-06-07,2269.0,0

In [142]:
# df_t.isnull().sum()

In [143]:
# df_t.loc[df_t['days_since_account_open'] < 0, 'days_since_account_open'] = np.nandf_t['account_open_issue_flag'] = df_t['days_since_account_open'].isna().astype(int)
# df_t['days_since_account_open'] = df_t['days_since_account_open'].fillna(
#     df_t['days_since_account_open'].median()
# )

In [144]:
df = pd.read_parquet("f_t2.parquet")
print(df.shape)
df.head(3)

(160153, 147)

,account_id,account_status,product_code,currency_code,account_opening_date,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [145]:
df_main = df.merge(
    df_t,
    on='account_id',
    how='left'
)
print(df_main.shape)
df_main.head(3)

(160153, 151)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag
0,ACCT_000000,active,200,1,2023-08-30,7982,515008.0,53720.31,K,Y,Y,Y,0,None,Y,2023-11-04,Y,50111.60,55554.79,66771.57,None,None,"95 Market Street, Guwahati",530055,Guwahati,Bihar,41,13.14,227.69,urban,PMJDY,CUST_000000,0,1950-07-15,2019-10-03,Y,Y,N,Y,Y,Y,N,Y,N,515008,515008,Suresh Mukherjee,M,2019-01-07,"231 Civil Lines, Vijayawada",91-6999889419,2022-11-28,N,N,NaN,0,117176.98,1,0.00,0,53720.31,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2023-08-30,None,792.0,1
1,ACCT_000002,active,1133,1,2019-08-05,5479,144074.0,9492.82,O,N,N,N,0,None,Y,2021-10-03,N,9169.02,6925.45,8737.84,None,None,"127 Industrial Area, Panaji",226076,Panaji,Telangana,3,12.47,489.68,semi-urban,REGULAR,CUST_000002,0,1985-08-01,1999-08-19,N,N,N,Y,N,Y,N,N,N,144074,144074,Swati Banerjee,F,2024-08-14,"271 Park Avenue, Chennai",91-7580284789,2021-05-12,N,N,NaN,0,NaN,0,-25821.38,1,0.00,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-08-05,None,792.0,1
2,ACCT_000003,active,146,1,2023-10-31,8227,190033.0,93286.70,S,N,Y,Y,3,None,Y,2024-10-25,N,86326.00,100171.75,78181.17,None,None,"123 Main Road, Dehradun",520010,Dehradun,Maharashtra,31,12.24,343.44,semi-urban,REGULAR,CUST_000003,0,1972-03-18,2018-04-28,N,Y,N,N,N,Y,N,N,N,190033,190033,Reyansh Patel,M,2024-07-13,"14 Park Avenue, Pune",91-9908446104,None,N,N,-158176.92,2,NaN,0,0.00,0,0.00,0,93286.7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2023-10-31,None,792.0,1

In [146]:
df_main.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                            9468
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                      9468
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                       68202
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
dtype: int64

In [147]:
object_cols = df_main.select_dtypes(include=['object']).columns
print("Object columns:", object_cols)
print("Total:", len(object_cols))

Object columns: Index(['account_id', 'account_status', 'account_opening_date_x',
       'product_family', 'nomination_flag', 'cheque_allowed', 'cheque_availed',
       'last_mobile_update_date', 'kyc_compliant', 'last_kyc_date',
       'rural_branch', 'freeze_date', 'unfreeze_date', 'branch_address',
       'branch_city', 'branch_state', 'branch_type', 'scheme_code',
       'customer_id', 'date_of_birth', 'relationship_start_date',
       'pan_available', 'aadhaar_available', 'passport_available',
       'mobile_banking_flag', 'internet_banking_flag', 'atm_card_flag',
       'demat_flag', 'credit_card_flag', 'fastag_flag', 'name', 'gender',
       'address_last_update_date', 'address', 'phone_number',
       'passbook_last_update_date', 'joint_account_flag', 'nri_flag',
       'most_common_channel', 'channel_max_amount', 'channel_min_amount',
       'least_common_channel', 'atm_deposit_types', 'account_opening_date_y',
       'last_transaction_date'],
      dtype='object')
Total: 45

In [148]:
df_acc.isnull().sum()

account_id                      0
account_status                  0
product_code                    0
currency_code                   0
account_opening_date            0
branch_code                     0
branch_pin                  15505
avg_balance                  9468
product_family                  0
nomination_flag                 0
cheque_allowed                  0
cheque_availed                  0
num_chequebooks                 0
last_mobile_update_date    135918
kyc_compliant                   0
last_kyc_date                   0
rural_branch                    0
monthly_avg_balance          9468
quarterly_avg_balance           0
daily_avg_balance               0
freeze_date                148372
unfreeze_date              156447
dtype: int64

In [149]:
df1 = df_main

In [150]:
no_txn_mask = df1["total_transactions"] == 0
no_txn_mask.sum()

np.int64(0)

In [151]:
df1["avg_balance_missing"] = df1["avg_balance_x"].isna().astype(int)

new_accounts = df1["days_since_account_open"] < 30
df1.loc[new_accounts & df1["avg_balance_x"].isna(), "avg_balance_x"] = 0

#fill with median WITHIN the same product_family
# because savings accounts and current accounts have very different balance profiles
df1["avg_balance_x"] = df1.groupby("product_family")["avg_balance_x"].transform(
    
    lambda x: x.fillna(x.median())
)
print(df1.shape)
df1.sample(3)

(160153, 152)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing
42113,ACCT_052664,active,100,1,2019-04-02,8769,141048.0,6509.33,S,N,Y,Y,1,None,Y,2022-08-03,N,6346.52,4888.11,8745.07,None,None,"182 Market Street, New Delhi",302023,New Delhi,Delhi,20,8.52,337.07,urban,REGULAR,CUST_052521,0,1974-07-04,2001-10-09,Y,N,N,N,Y,Y,N,Y,N,141048,141048,Prisha Banerjee,F,2018-06-26,"292 Station Road, Mumbai",91-8790094734,2020-08-27,Y,N,-909096.89,1,-53229.95,2,0.0,0,0.00,0,6509.33,1,2610.0,56.0,9384.0,541.0,2943.0,5682.0,35.0,UPD,946.0,UPD,UPD,1.0,1.0,1.0,2.0,IAD,7273.0,62528546.74,23957.297602,3766998.85,-19500.0,136142.636534,1000.00,30497693.58,32030853.16,2058300.00,3766998.85,0.952135,0.491571,0.508429,60377.655040,41418.0,3.0,2.0,7.0,28.0,1.430921,0.059645,10.000000,43.500000,0.055939,0.927586,4.0,52.0,0.980077,33.0,37.0,1.041600,3.0,0.001200,1.874813,7.0,0.025937,828.0,0.317241,828.0,14.633932,1.0,869.0,0.332950,869.0,1.0,0.001151,10.0,0.003831,"CRM,CDM",-1.002705e+06,-3838398.16,-1.047233e+06,-9.596534e+05,1207471.60,0.0,0.0,0.0,0.939464,0.037548,0.022989,0.0,1.0,2.0,1.0,4.0,0,2019-04-02,2025-06-28,2279.0,0,0
153651,ACCT_192050,active,1313,1,2020-11-21,6190,110212.0,288.73,K,Y,Y,N,0,None,Y,2021-10-25,N,240.41,305.35,369.51,None,None,"59 Market Street, Kolkata",560015,Kolkata,Uttarakhand,47,17.32,72.02,semi-urban,REGULAR,CUST_191471,0,2000-03-26,2001-11-29,Y,Y,N,N,Y,Y,N,Y,N,110212,110212,Komal Srivastava,F,2023-09-19,"326 Park Avenue, Indore",91-8458876784,2021-11-05,N,N,NaN,0,-349055.56,1,0.0,0,288.73,1,0.00,0,2139.0,53.0,9384.0,441.0,2017.0,2920.0,34.0,UPC,805.0,UPC,UPC,1.0,1.0,1.0,2.0,OPI,5411.0,43863511.70,20506.550584,2962350.98,-62000.0,112710.903997,871.64,21904397.86,21959113.84,1990000.00,2962350.98,0.997508,0.488546,0.511454,67887.640786,50407.5,3.0,2.0,7.0,19.0,1.272457,0.053052,8.875519,38.196429,0.050491,0.930341,3.0,22.0,0.989715,22.0,21.0,1.034867,3.0,0.000484,1.751055,7.0,0.019353,798.0,0.373072,798.0,14.771566,1.0,735.0,0.343619,735.0,1.0,0.001361,14.0,0.006545,"CRM,CDM",-9.980740e+05,-3307622.66,-9.528358e+05,-1.041286e+06,1908974.51,0.0,0.0,0.0,0.943899,0.030388,0.025713,0.0,1.0,2.0,1.0,4.0,0,2020-11-21,2025-06-28,1680.0,0,0
96210,ACCT_120483,active,169,1,2016-12-18,4910,500008.0,23573.90,S,N,Y,Y,0,None,Y,2025-06-07,N,25634.25,25492.20,35242.43,None,None,"15 Station Area, Srinagar",600090,Srinagar,Tamil Nadu,19,5.88,91.60,semi-urban,REGULAR,CUST_120123,0,1959-08-02,2021-10-09,Y,N,N,N,N,N,N,Y,N,500008,500008,Manoj Das,M,2019-07-09,"457 Nehru Road, Mumbai",91-8663176419,None,N,N,NaN,0,-17570.10,1,0.0,0,0.00,0,23573.90,1,1388.0,55.0,9384.0,270.0,5905.0,2921.0,33.0,UPC,490.0,NTD,UPD,1.0,1.0,1.0,1.0,MAD,4900.0,49736443.13,35833.172284,9867505.81,-285000.0,392837.020802,796.30,24374135.85,25362307.28,9867505.81,9210000.00,0.961038,0.511527,0.488473,113540.102379,78247.0,4.0,2.0,15.0,21.0,0.760965,0.031729,5.318008,23.133333,0.056196,0.922911,NaN,64.0,0.953890,44.0,32.0,1.025111,4.0,0.000000,1.436709,15.0,0.011463,507.0,0.365274,507.0,15.309748,1.0,480.0,0.345821,480.0,1.0,0.002083,2.0,0.001441,CDM,6.701273e+04,-9169261.34,1.440349e+05,-1.364470e+04,3241157.89,0.0,0.0,0.0,0.932997,0.026657,0.040346,0.0,1.0,3.0,1.0,6.0,1,2016-12-18,2025-06-28,3114.0,0,0

In [152]:
df1.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                      9468
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                       68202
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
dtype: int64

In [153]:
df3 = df1[["account_id","account_opening_date_y","account_opening_date_x"]]
print(df3.shape)
df3.sample(3)

(160153, 3)

         account_id account_opening_date_y account_opening_date_x
2163    ACCT_002743             2023-03-26             2023-03-26
64823   ACCT_081111             2024-01-15             2024-01-15
117257  ACCT_146692             2023-08-25             2023-08-25

In [154]:
df2 = df1
df2['active_tenure_days'] = (
    (pd.to_datetime(df2['account_opening_date_y']) - 
     pd.to_datetime(df2['relationship_start_date']))
    .dt.days
).fillna(0)
print(df2.shape)
df2.sample(3)

(160153, 153)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days
128220,ACCT_160447,active,100,1,2023-09-20,9770,560198.0,2322.05,S,N,Y,N,0,2025-02-28,Y,2023-06-05,N,2171.44,2747.10,1308.03,None,None,"166 Market Street, New Delhi",201049,New Delhi,Goa,15,9.71,107.23,urban,REGULAR,CUST_159970,0,1951-07-20,2000-12-04,Y,None,N,Y,N,Y,N,Y,N,560198,641052,Sanjay Hegde,M,2024-05-06,"96 MG Road, Bhopal",91-6391021418,None,N,N,NaN,0,-38257.21,2,0.0,0,0.00,0,2322.05,1,493.0,35.0,9384.0,105.0,5905.0,9355.0,30.0,UPC,187.0,UPC,UPC,1.0,1.0,1.0,1.0,CSD,7523.0,9446233.64,19160.717323,1010790.7,-1500.0,83396.550662,1000.0,3551334.47,5894899.17,442700.0,1010790.70,0.602442,0.507099,0.492901,113681.359756,80335.0,2.0,2.0,5.0,18.0,0.760802,0.031729,5.301075,22.409091,0.064909,0.918864,NaN,8.0,0.983773,8.0,7.0,1.010267,2.0,0.001027,1.431193,5.0,0.028746,161.0,0.326572,161.0,15.376500,1.0,143.0,0.290061,143.0,1.0,0.006993,1.0,0.002028,CDM,-613816.529533,-2741804.95,-561252.548240,-667894.699588,1305876.28,0.0,0.0,0.0,0.918864,0.038540,0.042596,0.0,1.0,2.0,1.0,3.0,0,2023-09-20,2025-06-28,647.0,0,0,8325
84242,ACCT_105534,active,1313,1,2021-06-22,5451,249028.0,50781.04,K,Y,Y,Y,1,None,Y,2023-10-28,N,49560.20,59618.76,72879.01,None,None,"76 Commercial Complex, Indore",721003,Indore,Odisha,38,16.47,184.44,rural,APY,CUST_105222,0,1968-07-10,2005-04-25,Y,Y,N,N,Y,N,N,N,Y,249028,249028,Meera Kumar,F,2020-03-18,"323 Civil Lines, Panaji",91-8501139100,2020-12-06,N,N,-63163.25,1,NaN,0,0.0,0,50781.04,1,0.00,0,1662.0,51.0,9384.0,366.0,5651.0,5977.0,34.0,UPC,602.0,UPC,P2A,1.0,1.0,1.0,2.0,OPI,5251.0,49557688.11,29818.103556,4314000.0,-43000.0,225764.803265,1000.0,27614109.38,21943578.73,3726100.0,4314000.00,1.258414,0.471721,0.528279,76307.866346,55243.0,3.0,2.0,7.0,17.0,1.132153,0.047204,7.914286,33.918367,0.045728,0.938026,3.0,17.0,0.989771,17.0,16.0,1.044192,3.0,0.002315,1.679245,6.0,0.019954,586.0,0.352587,586.0,14.669817,1.0,525.0,0.315884,525.0,1.0,0.001905,4.0,0.002407,"CDM,CRM",-894346.607738,-5342175.33,-821829.610638,-959099.826105,7747944.02,0.0,0.0,0.0,0.936823,0.034296,0.028881,0.0,1.0,2.0,1.0,4.0,0,2021-06-22,2025-06-28,1467.0,0,0,5902
72474,ACCT_090762,active,100,1,2022-03-04,6474,249034.0,0.00,S,N,Y,Y,3,None,Y,2022-04-13,N,0.00,0.00,0.00,None,None,"17 Commercial Complex, Dehradun",735036,Dehradun,Punjab,37,11.29,149.64,semi-urban,REGULAR,CUST_090488,0,1968-08-31,2012-07-31,Y,None,Y,N,N,Y,N,N,N,249034,249034,Prisha Shah,F,2023-10-06,"235 Park Avenue, Srinagar",91-7983859448,None,N,N,NaN,0,NaN,0,0.0,0,0.00,0,0.00,1,1259.0,48.0,9384.0,263.0,5905.0,9355.0,30.0,UPC,476.0,IPM,END,1.0,1.0,1.0,1.0,IAD,6300.0,38693252.66,30733.322208,8952000.0,-31.5,287004.602378,1000.0,20824710.63,17868542.03,8952000.0,2695832.36,1.165440,0.482129,0.517871,83270.903816,64202.5,4.0,2.0,6.0,15.0,1.037923,0.043265,7.235632,31.475000,0.057188,0.927720,NaN,11.0,0.991263,11.0,10.0,1.029532,4.0,0.001504,1.539744,5.0,0.025342,435.0,0.345512,435.0,14.643317,1.0,429.0,0.340747,429.0,1.0,0.002331,2.0,0.001589,"CRM,CDM",27660.946497,-4379510.69,-125035.946376,169818.943390,5022330.79,0.0,0.0,0.0,0.932486,0.036537,0.030977,0.0,1.0,2.0,1.0,3.0,0,2022-03-04,2025-06-28,1212.0,0,0,3503

In [155]:
df2.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                      9468
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                       68202
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
dtype: int64

In [156]:
df3 = df2

In [157]:
# 1️⃣ Create a flag for missing monthly average balance
df3["monthly_avg_balance_missing"] = df3["monthly_avg_balance"].isna().astype(int)

# 2️⃣ If the account is very new (<30 days) and balance is missing → set to 0
new_accounts = df3["days_since_account_open"] < 30
df3.loc[new_accounts & df3["monthly_avg_balance"].isna(), "monthly_avg_balance"] = 0

# 3️⃣ Fill remaining missing values using median within the same product_family
df3["monthly_avg_balance"] = df3.groupby("product_family")["monthly_avg_balance"].transform(
    lambda x: x.fillna(x.median())
)

print(df3.shape)
df3.sample(3)

(160153, 154)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing
107642,ACCT_134680,active,1133,1,2015-12-11,6452,500011.0,41281.93,O,Y,N,N,0,None,Y,2024-10-18,N,33413.60,52468.41,42266.46,None,None,"50 Industrial Area, Bhubaneswar",500157,Bhubaneswar,Jharkhand,12,16.11,468.44,urban,REGULAR,CUST_134280,0,1989-10-27,2000-09-06,Y,None,N,N,N,N,Y,N,N,500011,670008,Rahul Jain,M,2018-07-10,"3 Civil Lines, Thiruvananthapuram",91-8277761820,2022-03-22,Y,Y,NaN,0,NaN,0,-58155.72,1,0.0,0,0.0,0,13032.0,58.0,9384.0,2789.0,2017.0,2557.0,35.0,UPC,4851.0,STD,UPD,1.0,4.0,1.0,4.0,IAD,5941.0,4.549453e+08,34909.860398,84365144.5,-413826.02,791344.447106,1000.00,1.970106e+08,2.579347e+08,16241900.0,84365144.50,0.763800,0.461249,0.538751,12089.404881,5901.0,5.0,3.0,18.0,69.0,7.144737,0.297793,49.931034,217.200000,0.056630,0.926258,118.0,10.0,0.999233,9.0,10.0,1.207411,4.0,0.013040,4.846069,9.0,0.273701,5487.0,0.421041,5487.0,15.367290,1.0,4475.0,0.343386,4475.0,1.0,0.000223,31.0,0.002379,"CRM,CDM",-3.301259e+07,-80926507.61,-3.306185e+07,-3.297041e+07,11571057.23,0.0,0.0,0.0,0.961172,0.034223,0.000000,0.004604,1.0,4.0,3.0,10.0,0,2015-12-11,2025-06-28,3487.0,0,0,5574,0
86329,ACCT_108132,active,169,1,2023-10-11,1057,248027.0,0.00,S,N,Y,Y,0,2025-03-15,Y,2022-12-07,N,0.00,0.00,0.00,None,None,"134 Industrial Area, Pune",585022,Pune,Goa,48,6.37,237.30,urban,REGULAR,CUST_107806,0,1988-11-03,2002-07-28,Y,N,N,N,Y,N,N,N,N,248027,248027,Manoj Deshpande,M,2021-11-12,"417 Park Avenue, Vijayawada",91-7109701438,None,Y,N,NaN,0,NaN,0,0.00,0,0.0,0,0.0,1,826.0,43.0,9384.0,174.0,2557.0,6101.0,31.0,UPD,308.0,UPD,UPC,1.0,1.0,1.0,2.0,SID,5169.0,2.215312e+07,26819.752627,7363000.0,-28000.00,274938.485964,798.56,1.377891e+07,8.374201e+06,7363000.0,1657397.91,1.645400,0.491525,0.508475,65543.624242,46048.0,3.0,2.0,6.0,16.0,1.317384,0.054986,9.177778,39.333333,0.072639,0.905569,2.0,28.0,0.966102,28.0,27.0,1.035176,3.0,0.001256,1.804444,6.0,0.011852,312.0,0.377724,312.0,14.554849,1.0,244.0,0.295400,244.0,1.0,0.004098,2.0,0.002421,"CDM,CRM",1.766093e+06,-1470386.09,1.692063e+06,1.837655e+06,6214267.35,0.0,0.0,0.0,0.943099,0.032688,0.024213,0.000000,1.0,2.0,1.0,3.0,-1,2023-10-11,2025-06-28,626.0,0,0,7745,0
83616,ACCT_104745,active,804,1,2023-12-20,7907,670034.0,2465.97,O,Y,N,N,0,None,Y,2022-12-13,N,2009.22,3197.24,1839.89,None,None,"125 Market Street, Chennai",313002,Chennai,Chhattisgarh,21,19.20,428.00,rural,REGULAR,CUST_104435,0,1994-08-28,2010-03-27,N,Y,N,N,N,N,N,Y,N,600075,600087,Diya Kulkarni,F,2018-09-04,"163 Sector 20, Pune",91-9992470203,2021-08-05,N,N,NaN,0,-29250.43,2,-45497.87,1,0.0,0,0.0,0,1681.0,50.0,9384.0,356.0,2920.0,5905.0,35.0,UPC,745.0,UPC,IPM,1.0,2.0,1.0,2.0,IAD,6051.0,7.493392e+07,44576.990422,12545000.0,-88100.00,485578.943256,959.48,1.957040e+07,5.536352e+07,2116300.0,12545000.00,0.353489,0.458656,0.541344,28598.498214,15750.5,4.0,3.0,11.0,29.0,3.017953,0.125946,21.012500,88.473684,0.053540,0.932183,6.0,22.0,0.986913,21.0,22.0,1.092277,4.0,0.003818,2.992263,9.0,0.059540,448.0,0.266508,448.0,537.814050,1.0,610.0,0.362879,610.0,1.0,0.001639,3.0,0.001785,"CDM,CRM",-1.950192e+07,-39795037.02,-1.928667e+07,-1.968429e+07,3130435.54,0.0,0.0,0.0,0.963712,0.025580,0.000000,0.010708,1.0,2.0,2.0,8.0,-1,2023-12-20,2025-06-28,556.0,0,0,5016,0

In [158]:
df3.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                       68202
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
dtype: int64

In [159]:
df4 = df3

In [160]:
df4['account_frozen_flag'] = df4['freeze_date'].notna().astype(int)
print(df4.shape)
df4.sample(3)

(160153, 155)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag
64367,ACCT_080550,active,113,1,2023-06-01,7014,313048.0,4294.96,S,Y,Y,N,0,None,Y,2025-03-04,N,4951.53,5091.64,4278.89,None,None,"78 Industrial Area, Visakhapatnam",176020,Visakhapatnam,Telangana,5,21.48,384.47,urban,REGULAR,CUST_080312,0,1999-04-17,2024-02-01,Y,None,N,Y,N,N,N,N,N,313048,313048,Myra Hegde,F,2021-01-21,"41 Nehru Road, Mumbai",91-8725564614,2024-10-25,N,N,NaN,0,NaN,0,0.0,0,0.00,0,4294.96,1,1857.0,52.0,9384.0,401.0,2017.0,5905.0,34.0,UPC,753.0,FTC,UPD,1.0,2.0,1.0,2.0,IAD,6300.0,54317662.70,29250.222240,5708975.22,-110500.00,236034.701028,965.93,33502868.39,20814794.31,5708975.22,1750032.47,1.609570,0.488422,0.511578,35277.098060,19424.0,3.0,2.0,9.0,30.0,2.446640,0.102095,17.036697,74.280000,0.058697,0.924071,7.0,6.0,0.996769,6.0,5.0,1.068966,3.0,0.007598,2.162996,5.0,0.140132,770.0,0.414647,770.0,14.987058,1.0,657.0,0.353796,657.0,1.0,0.001522,2.0,0.001077,CRM,2.495749e+06,-2578379.54,2.480225e+06,2.510570e+06,12759978.85,0.0,0.0,0.0,0.955843,0.030695,0.013463,0.0,1.0,2.0,1.0,5.0,-1,2023-06-01,2025-06-28,758.0,0,0,-245,0,0
156857,ACCT_196062,active,1313,1,2024-01-25,6163,751018.0,47402.45,K,N,Y,N,0,None,Y,2021-06-01,N,45190.65,60141.39,30119.39,None,None,"55 Commercial Complex, Chennai",500165,Chennai,Maharashtra,37,7.57,217.21,urban,REGULAR,CUST_195475,0,2003-10-10,1996-07-08,Y,None,Y,N,N,Y,N,N,N,751018,751018,Vihaan Yadav,M,2019-05-18,"279 Park Avenue, Jaipur",91-8506857398,None,N,N,NaN,0,NaN,0,0.0,0,47402.45,1,-188.79,1,927.0,45.0,9384.0,192.0,2944.0,5905.0,33.0,UPC,358.0,UPC,UPD,1.0,1.0,1.0,2.0,SCW,6300.0,18779906.49,20258.798803,3295000.00,-7219.59,132622.685934,1000.00,9105430.00,9674476.49,3295000.00,1829500.00,0.941181,0.448759,0.551241,48492.045356,27357.0,3.0,2.0,8.0,24.0,1.779271,0.074309,12.360000,51.500000,0.051780,0.932039,NaN,17.0,0.981661,17.0,16.0,1.050057,3.0,0.002275,2.111380,6.0,0.037744,375.0,0.404531,375.0,15.155928,1.0,309.0,0.333333,309.0,1.0,0.003236,0.0,0.000000,None,-9.681423e+05,-2943541.67,-9.471366e+05,-9.852427e+05,1210645.92,0.0,0.0,0.0,0.937433,0.044229,0.018339,0.0,1.0,2.0,1.0,5.0,0,2024-01-25,2025-06-28,520.0,0,0,10062,0,0
16667,ACCT_020887,active,1035,1,2023-03-31,6486,695008.0,355204.55,K,Y,Y,N,0,None,Y,2022-03-16,N,389780.46,363737.62,518148.65,None,None,"41 Main Road, Jaipur",226044,Jaipur,West Bengal,23,15.13,277.14,rural,REGULAR,CUST_020828,0,1964-08-26,2017-09-14,Y,Y,N,N,N,Y,N,N,N,695008,695008,Pranav Joshi,M,2025-03-18,"397 Civil Lines, Thiruvananthapuram",91-6567279050,None,N,N,NaN,0,NaN,0,0.0,0,355204.55,1,0.00,0,1391.0,51.0,9384.0,306.0,4106.0,9384.0,34.0,UPC,563.0,FTD,UPD,1.0,1.0,1.0,2.0,ASD,5812.0,56860220.40,40877.225306,28614513.12,-1022.28,772461.775692,996.17,12653952.09,44206268.31,1520472.39,28614513.12,0.286248,0.465852,0.534148,50906.225899,34731.0,3.0,2.0,8.0,23.0,1.696341,0.070764,11.788136,51.518519,0.058950,0.925953,1.0,19.0,0.986341,19.0,18.0,1.054033,2.0,0.002156,1.998485,7.0,0.032563,447.0,0.321352,447.0,15.576195,1.0,498.0,0.358016,498.0,1.0,0.002008,1.0,0.000719,CRM,-2.262409e+07,-34059957.43,-2.218764e+07,-2.300474e+07,402574.62,0.0,0.0,0.0,0.956147,0.024443,0.019410,0.0,1.0,2.0,1.0,6.0,-1,2023-03-31,2025-06-28,820.0,0,0,2024,0,0

In [161]:
df4.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                       68202
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
dtype: int64

In [162]:
df5 = df4

In [163]:
df5["aadhaar_available"] = df5["aadhaar_available"].map({
    "yes": 1,
    "no": 0
})
df5["aadhaar_available"] = df5["aadhaar_available"].fillna(-1)
print(df5.shape)
df5.sample(3)

(160153, 155)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag
96750,ACCT_121158,active,193,1,2022-06-11,3604,515006.0,8816.00,K,N,Y,Y,1,None,Y,2024-07-12,Y,9407.680,11241.05,5947.41,None,None,"62 Industrial Area, Ahmedabad",411025,Ahmedabad,Delhi,42,18.33,497.46,urban,PMJJBY,CUST_120795,0,1968-03-29,2017-02-07,N,-1.0,N,N,Y,N,N,Y,N,400093,400093,Atharva Mukherjee,M,2019-02-20,"331 Station Road, Srinagar",91-9505717825,2024-10-17,N,N,NaN,0,-54226.85,2,0.0,0,8816.0,1,0.00,0,3335.0,58.0,9384.0,637.0,9355.0,2943.0,34.0,UPC,1216.0,UPD,UPC,1.0,2.0,1.0,2.0,CTC,5200.0,78528269.66,23546.707544,7005000.0,-36697.75,188422.361526,1000.00,32835884.14,45692385.52,7005000.0,4439676.32,0.718629,0.464468,0.535532,28844.168866,15694.0,3.0,3.0,10.0,43.0,2.993716,0.124841,20.843750,90.135135,0.054273,0.925937,11.0,9.0,0.997301,9.0,8.0,1.071382,3.0,0.005083,2.682832,7.0,0.123992,1344.0,0.402999,1344.0,670.411362,1.0,1140.0,0.341829,1140.0,1.0,0.000877,9.0,0.002699,"CDM,CRM",-3.670313e+06,-12879729.67,-3.656789e+06,-3.682043e+06,2851959.41,0.0,0.0,0.0,0.955022,0.034183,0.010795,0.0,1.0,2.0,2.0,5.0,-1,2022-06-11,2025-06-28,1113.0,0,0,1950,0,0
135593,ACCT_169628,active,161,1,2022-02-02,5181,785045.0,4551.00,S,N,Y,N,0,2025-01-26,Y,2022-06-29,N,4518.235,1543.09,874.98,None,None,"59 Main Road, Mumbai",530015,Mumbai,Assam,31,13.47,151.23,urban,REGULAR,CUST_169123,0,1978-10-12,1997-06-30,N,-1.0,Y,Y,Y,N,N,N,N,785045,785045,Amit Chatterjee,M,2024-04-20,"304 Gandhi Nagar, Kochi",91-8804388449,2023-10-28,N,N,-844346.99,3,NaN,0,0.0,0,0.0,0,0.00,1,1462.0,50.0,9384.0,312.0,2017.0,2955.0,31.0,UPC,563.0,UPD,ETD,1.0,1.0,1.0,1.0,SID,5941.0,31236191.82,21365.384282,3128000.0,-81000.00,129699.539176,900.00,12743503.69,18492688.13,1596500.0,3128000.00,0.689110,0.448700,0.551300,73459.376454,53459.0,3.0,2.0,8.0,16.0,1.176187,0.049037,8.213483,35.658537,0.047880,0.934337,5.0,28.0,0.980848,28.0,27.0,1.032486,3.0,0.000000,1.716687,7.0,0.012335,474.0,0.324213,474.0,14.844143,1.0,490.0,0.335157,490.0,1.0,0.002041,4.0,0.002736,"CRM,CDM",-2.525183e+06,-6011173.41,-2.468676e+06,-2.571174e+06,764695.74,0.0,0.0,0.0,0.941860,0.030780,0.027360,0.0,1.0,2.0,1.0,4.0,0,2022-02-02,2025-06-28,1242.0,0,1,8983,1,0
90961,ACCT_113925,active,169,1,2020-05-25,4118,500198.0,2854.96,S,Y,Y,N,0,None,Y,2023-08-29,N,2686.560,2848.82,1888.28,None,None,"127 Industrial Area, Srinagar",500077,Srinagar,Telangana,20,8.95,188.92,urban,REGULAR,CUST_113585,0,2001-04-04,2004-06-17,N,-1.0,N,N,N,N,N,N,N,500198,636024,Reyansh Nair,M,2023-12-31,"63 Gandhi Nagar, Hyderabad",91-9991761219,None,N,N,NaN,0,NaN,0,0.0,0,0.0,0,2854.96,1,2156.0,52.0,9384.0,437.0,5905.0,2943.0,34.0,UPC,832.0,UPD,UPC,1.0,1.0,1.0,1.0,SID,7273.0,44150798.87,20478.107083,3289000.0,-21252.21,121960.341439,826.96,22797245.53,21353553.34,3289000.0,3237643.84,1.067609,0.484230,0.515770,73053.653828,53500.0,3.0,2.0,7.0,16.0,1.182666,0.049300,8.260536,35.933333,0.051484,0.934137,5.0,22.0,0.989796,22.0,13.0,1.035300,3.0,0.003627,1.660989,6.0,0.029267,670.0,0.310761,670.0,15.299466,1.0,752.0,0.348794,752.0,1.0,0.001330,8.0,0.003711,"CDM,CRM",-3.486443e+06,-5993089.89,-3.445365e+06,-3.525009e+06,1565384.50,0.0,0.0,0.0,0.942022,0.030148,0.027829,0.0,1.0,2.0,1.0,4.0,0,2020-05-25,2025-06-28,1860.0,0,0,5821,0,0

In [164]:
df5.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                               126693
loan_count                                  0
cc_sum                                 134411
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
dtype: int64

nul value of loan_sum and cc_sum 

Fill with 0
Because absence of loan/credit card ≠ missing data, it means no activity.

In [165]:
df5['loan_sum'] = df5['loan_sum'].fillna(0)
df5['cc_sum'] = df5['cc_sum'].fillna(0)
print(df5.shape)
df5.sample(3)

(160153, 155)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag
52090,ACCT_065158,active,100,1,2017-08-02,7236,360048.0,997.49,S,Y,Y,Y,0,None,Y,2022-04-04,N,888.47,702.12,504.18,2023-04-12,2023-06-04,"172 Market Street, Guwahati",110246,Guwahati,Bihar,22,24.68,197.29,urban,REGULAR,CUST_064970,0,1969-06-12,1997-01-11,N,-1.0,N,Y,N,Y,N,N,N,360048,360048,Sanjay Pandey,M,2021-06-09,"384 Civil Lines, Hyderabad",91-7863715651,2023-10-27,N,N,0.00,0,0.00,0,0.00,0,0.0,0,997.49,1,5445.0,58.0,9384.0,1133.0,2557.0,5905.0,35.0,UPC,2028.0,UPC,UPC,1.0,2.0,1.0,2.0,SCW,5941.0,1.319926e+08,24241.058062,9291000.00,-128400.0,193296.169176,900.0,60557051.81,71435509.34,5116800.00,9291000.00,0.847716,0.478788,0.521212,28934.253123,14934.5,4.0,3.0,12.0,33.0,2.985197,0.124437,20.862069,90.750000,0.059137,0.925803,27.0,12.0,0.997796,12.0,11.0,1.088087,4.0,0.004468,2.892748,9.0,0.090968,1680.0,0.308540,1680.0,15.108628,1.0,1837.0,0.337374,1837.0,1.0,0.000544,13.0,0.002388,CDM,-9.533575e+06,-16401311.34,-9.505481e+06,-9.559382e+06,119490.66,0.0,0.0,0.0,0.951331,0.038017,0.010652,0.000000,1.0,3.0,2.0,6.0,-1,2017-08-02,2025-06-28,2887.0,0,0,7508,0,1
75126,ACCT_094111,active,146,1,2020-12-12,5036,800067.0,4260.70,S,Y,Y,N,0,2025-01-22,Y,2024-06-11,N,4471.78,5293.57,4171.20,None,None,"166 Commercial Complex, Vijayawada",848001,Vijayawada,Jammu & Kashmir,16,24.10,146.89,semi-urban,REGULAR,CUST_093832,0,1995-07-21,2014-08-18,Y,-1.0,N,N,N,N,N,Y,N,400187,400187,Manoj Das,M,2016-09-07,"246 Station Road, Patna",91-8625976802,2022-01-03,N,N,-481755.11,3,-95025.79,1,0.00,0,0.0,0,4260.70,1,4401.0,57.0,9384.0,913.0,2017.0,2557.0,35.0,UPC,1822.0,UPD,UPC,1.0,2.0,1.0,2.0,ASD,7399.0,9.683737e+07,22003.492320,6289013.47,-400000.0,149692.534476,1000.0,46835866.13,50001503.57,2249000.00,6289013.47,0.936689,0.462622,0.537378,32572.765227,17778.0,5.0,3.0,11.0,35.0,2.651205,0.110542,18.491597,80.018182,0.053851,0.928653,15.0,16.0,0.996364,16.0,15.0,1.081683,4.0,0.003494,2.699121,9.0,0.064476,1214.0,0.275846,1214.0,1468.043402,1.0,1553.0,0.352874,1553.0,1.0,0.000644,6.0,0.001363,"CRM,CDM",-3.873848e+06,-9697752.41,-3.901238e+06,-3.850268e+06,4385733.39,0.0,0.0,0.0,0.959555,0.028175,0.012270,0.000000,1.0,3.0,2.0,5.0,-1,2020-12-12,2025-06-28,1659.0,0,0,2308,0,0
138446,ACCT_173125,active,804,1,2023-08-06,2871,360056.0,-254046.39,O,N,N,N,0,None,Y,2023-05-22,N,-279221.69,-183067.37,-314845.12,None,None,"120 Commercial Complex, Patna",700124,Patna,Chhattisgarh,3,24.17,130.57,rural,REGULAR,CUST_172610,0,2002-02-21,2003-12-16,N,-1.0,N,Y,N,Y,N,N,N,360056,360056,Advik Mehta,M,2019-04-03,"77 MG Road, Bhubaneswar",91-6178092512,2022-06-04,N,N,0.00,0,0.00,0,136047.02,1,0.0,0,0.00,0,768.0,45.0,9384.0,159.0,5905.0,9355.0,32.0,UPC,317.0,IPM,UPC,1.0,1.0,1.0,1.0,CHQ,5200.0,1.456329e+07,18962.612240,1482729.81,1.0,93447.939904,1000.0,8468475.58,6094810.62,1482729.81,605000.00,1.389457,0.451823,0.548177,77968.589309,56961.0,2.0,2.0,6.0,14.0,1.108225,0.046229,7.757576,33.391304,0.052083,0.933594,NaN,5.0,0.993490,4.0,5.0,1.028378,2.0,0.004730,1.503356,4.0,0.080947,233.0,0.303385,233.0,15.055640,1.0,270.0,0.351562,270.0,1.0,0.003704,2.0,0.002604,CDM,4.204139e+05,-707345.76,4.672646e+05,3.817982e+05,2126245.33,0.0,0.0,0.0,0.942708,0.028646,0.000000,0.028646,1.0,2.0,1.0,3.0,-1,2023-08-06,2025-06-28,692.0,0,0,7173,0,0

In [166]:
df5.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
dtype: int64

In [167]:
# df5.to_parquet("df_final.parquet", index=False)

### Handle transaction part : -

In [168]:
df6 = df5

In [169]:
# create zero transaction flag column
df6['zero_transaction_flag'] = df6['total_transactions'].isna().astype(int)
# df6["zero_transaction_flag"].values_counts()
print(df6.shape)
df6.sample(3)

(160153, 156)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag
25543,ACCT_031980,frozen,106,1,2023-10-10,4182,NaN,-29304.02,S,N,Y,Y,0,None,Y,2023-06-06,N,-25510.830,-35535.92,-26072.99,2021-08-28,None,"175 Market Street, Mumbai",743026,Mumbai,West Bengal,48,9.85,382.24,urban,REGULAR,CUST_031886,0,1991-02-27,1996-06-07,Y,-1.0,N,N,N,Y,N,N,N,411077,560035,Arnav Sharma,M,2022-12-13,"483 Nehru Road, Jaipur",91-8908230647,None,N,N,-372038.86,1,0.0,0,0.0,0,0.00,0,-29304.02,1,61.0,29.0,7311.0,6.0,6101.0,5651.0,5.0,NTD,15.0,UPC,FTC,1.0,1.0,1.0,2.0,FTC,1139.0,2.166562e+06,35517.404754,80838.82,1386.36,18941.867695,45952.00,1085538.79,1081022.90,70815.79,80838.82,1.004177,0.557377,0.442623,1.588120e+06,55500.0,2.0,1.0,5.0,15.0,0.055254,0.002305,0.386076,1.648649,0.000000,1.000000,NaN,61.0,0.000000,34.0,27.0,1.089286,2.0,0.000000,1.794118,5.0,0.000000,0.0,0.000000,0.0,NaN,0.0,0.0,0.000000,0.0,NaN,NaN,0.0,0.000000,None,0.000000e+00,0.00,0.000000e+00,0.000000e+00,0.00,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,0,2023-10-10,2024-03-29,171.0,0,0,9986,0,1,0
143184,ACCT_178972,active,202,1,2023-01-31,7314,751042.0,2370.79,K,N,Y,Y,1,None,Y,2022-05-04,N,2471.850,2354.17,2009.65,None,None,"46 Main Road, Shimla",313035,Shimla,Karnataka,30,13.01,144.62,semi-urban,PMJDY,CUST_178435,0,2001-04-15,2009-02-28,N,-1.0,N,Y,N,Y,N,N,N,380058,380058,Manoj Pandey,M,2018-11-07,"223 Nehru Road, Bhubaneswar",91-7373880805,None,N,N,0.00,0,0.0,0,0.0,0,2370.79,1,0.00,0,3396.0,56.0,9384.0,763.0,2017.0,2199.0,34.0,UPC,1269.0,FTC,STC,1.0,3.0,1.0,3.0,SCW,4816.0,1.269710e+08,37388.398292,47129188.78,-490416.94,845345.521023,991.47,85398357.58,41572643.02,47129188.78,4670204.37,2.054196,0.460542,0.539458,2.236748e+04,11781.0,3.0,2.0,14.0,41.0,3.859091,0.160986,26.952381,113.200000,0.053298,0.933157,16.0,8.0,0.997644,8.0,7.0,1.102606,3.0,0.008083,3.046045,7.0,0.183587,1107.0,0.325972,1107.0,1413.939473,1.0,1213.0,0.357185,1213.0,1.0,0.000824,7.0,0.002061,"CDM,CRM",1.063642e+07,-7998829.19,1.003396e+07,1.115075e+07,45383021.32,0.0,0.0,0.0,0.959069,0.032391,0.008539,0.0,1.0,3.0,2.0,6.0,-1,2023-01-31,2025-06-28,879.0,0,0,5085,0,0,0
43905,ACCT_054934,active,100,1,2024-01-08,5843,462030.0,4551.00,S,Y,Y,Y,1,None,Y,2025-02-11,N,4518.235,137196.90,75432.26,None,None,"63 Market Street, Bhubaneswar",560088,Bhubaneswar,Punjab,22,23.85,415.58,urban,PMSBY,CUST_054784,0,1979-05-17,2012-05-26,Y,-1.0,N,N,Y,N,N,N,N,462030,462030,Anvi Menon,F,2016-12-05,"55 Temple Street, Kochi",91-9689876936,2025-06-27,N,N,-1524306.58,3,0.0,0,0.0,0,0.00,0,0.00,1,875.0,44.0,9384.0,204.0,4106.0,6101.0,34.0,UPD,323.0,UPD,UPC,1.0,1.0,1.0,2.0,ASD,3478.0,2.332855e+07,26661.203097,3632100.00,-20000.00,177697.330256,975.75,10493194.56,12835358.15,3632100.00,1864883.93,0.817523,0.467429,0.532571,5.322618e+04,36577.5,3.0,2.0,6.0,17.0,1.623377,0.067709,11.363636,48.611111,0.054857,0.926857,3.0,14.0,0.984000,14.0,13.0,1.040670,3.0,0.002990,1.952830,5.0,0.032390,302.0,0.345143,302.0,14.990936,1.0,280.0,0.320000,280.0,1.0,0.003571,5.0,0.005714,"CRM,CDM",-9.830823e+05,-3833806.68,-8.923154e+05,-1.062747e+06,1046629.39,0.0,0.0,0.0,0.942857,0.037714,0.019429,0.0,1.0,2.0,1.0,3.0,-1,2024-01-08,2025-06-29,538.0,0,1,4244,1,0,0

In [170]:
df6.zero_transaction_flag.value_counts()

zero_transaction_flag
0    159776
1       377
Name: count, dtype: int64

In [171]:
df6.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                        377
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                  377
avg_transaction_amount                    377
max_transaction_amount                    377
min_transaction_amount                    377
std_transaction_amount                    377
median_transaction_amount                 377
total_credit_amount                       377
total_debit_amount                        377
max_credit_amount                         396
max_debit_amount                          405
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [172]:
df7 = df6

In [173]:
cols_fill_zero = [
    'total_transactions',
    'total_transaction_amount',
    'avg_transaction_amount',
    'max_transaction_amount',
    'min_transaction_amount',
    'std_transaction_amount',
    'median_transaction_amount',
    'total_credit_amount',
    'total_debit_amount',
    'max_credit_amount',
    'max_debit_amount'
]

df7[cols_fill_zero] = df7[cols_fill_zero].fillna(0)
print(df7.shape)
df7.sample(3)

(160153, 156)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag
125732,ACCT_157342,active,200,1,2020-12-21,8216,636033.0,0.00,K,N,Y,N,0,None,Y,2022-06-03,N,0.00,0.00,0.00,None,None,"15 Main Road, Bangalore",226076,Bangalore,Rajasthan,26,12.97,370.36,urban,REGULAR,CUST_156879,0,1947-09-26,1997-05-20,N,-1.0,N,N,Y,Y,N,N,N,110193,110193,Manoj Hegde,M,2015-11-06,"175 Nehru Road, Jodhpur",91-7614810669,2023-09-24,N,N,0.00,0,0.0,0,0.00,0,0.0,1,0.00,0,7692.0,58.0,9384.0,1658.0,2017.0,5905.0,35.0,UPC,2836.0,P2A,UPD,1.0,3.0,1.0,3.0,SCW,5699.0,2.195848e+08,28547.159388,59750701.85,-2675000.00,692859.026451,1000.0,1.333919e+08,8.619283e+07,59750701.85,3550000.00,1.547599,0.462559,0.537441,18550.610974,9652.0,4.0,3.0,18.0,47.0,4.656174,0.194081,32.593220,139.854545,0.060062,0.919657,45.0,22.0,0.997140,22.0,21.0,1.142152,4.0,0.003903,4.284731,12.0,0.084859,2856.0,0.371295,2856.0,751.837587,1.0,2738.0,0.355954,2738.0,1.0,0.000365,23.0,0.002990,"CDM,CRM",4.726218e+07,-6390700.92,4.721666e+07,4.730135e+07,62362886.92,0.0,0.0,0.0,0.954108,0.038872,0.007020,0.000000,1.0,3.0,2.0,8.0,0,2020-12-21,2025-06-29,1651.0,0,0,8616,0,0,0
16857,ACCT_021126,active,804,1,2020-04-25,7120,600035.0,98051.95,O,N,N,N,0,None,Y,2023-11-21,N,81477.33,110574.71,114137.65,None,None,"106 Commercial Complex, Kolkata",305035,Kolkata,Jammu & Kashmir,36,20.59,217.49,semi-urban,REGULAR,CUST_021066,0,1969-08-30,2009-11-04,Y,-1.0,Y,N,N,Y,N,N,N,600035,600035,Anirudh Das,M,2015-12-22,"290 Station Road, Jodhpur",91-8303743632,2020-08-22,N,N,-803880.45,1,0.0,0,-56883.03,1,0.0,0,0.00,0,9080.0,58.0,9384.0,1941.0,2557.0,2557.0,35.0,UPC,3789.0,UPC,IPM,1.0,3.0,1.0,3.0,SCW,5699.0,2.634573e+08,29015.118466,14638018.11,-368200.00,269844.428962,1000.0,1.327890e+08,1.306683e+08,14638018.11,8746000.00,1.016230,0.459692,0.540308,17348.520322,8819.0,5.0,3.0,16.0,56.0,4.978070,0.207524,34.789272,151.333333,0.056278,0.925000,61.0,20.0,0.997797,19.0,20.0,1.151876,5.0,0.004674,4.447811,13.0,0.097910,3128.0,0.344493,3128.0,15.518011,1.0,3282.0,0.361454,3281.0,2.0,0.000609,14.0,0.001542,"CDM,CRM",4.958654e+06,-8798850.27,4.960450e+06,4.957126e+06,14184979.43,0.0,0.0,0.0,0.966960,0.026432,0.000000,0.006608,1.0,3.0,2.0,7.0,-1,2020-04-25,2025-06-28,1890.0,0,0,3825,0,0,0
25117,ACCT_031459,active,106,1,2018-06-07,1036,560104.0,468.94,S,N,Y,N,0,None,Y,2021-10-28,N,448.08,372.83,653.78,None,None,"186 Market Street, Nagpur",620069,Nagpur,Bihar,27,6.73,416.62,urban,PMJJBY,CUST_031368,0,1958-08-29,2008-08-12,N,-1.0,Y,N,N,N,N,N,N,560104,560104,Manoj Bhat,M,2021-03-02,"69 Sector 37, Hyderabad",91-6596279715,None,N,N,0.00,0,0.0,0,0.00,0,0.0,0,468.94,1,2369.0,54.0,9384.0,469.0,2017.0,5905.0,35.0,UPC,895.0,UPC,UPD,1.0,1.0,1.0,2.0,SCW,4816.0,6.830054e+07,28830.958772,11567736.82,-34806.55,275661.081428,1000.0,3.607553e+07,3.222501e+07,11567736.82,3388259.13,1.119488,0.470241,0.529759,66522.622044,47377.5,3.0,2.0,8.0,21.0,1.298794,0.054137,9.076628,39.483333,0.053609,0.930350,7.0,26.0,0.989025,26.0,25.0,1.044228,3.0,0.001769,1.813586,8.0,0.018498,868.0,0.366399,868.0,15.509106,1.0,809.0,0.341494,809.0,1.0,0.001236,4.0,0.001688,"CDM,CRM",-2.557070e+05,-6651448.58,-2.800956e+05,-2.340585e+05,5058125.05,0.0,0.0,0.0,0.940481,0.034192,0.025327,0.000000,1.0,2.0,1.0,4.0,-1,2018-06-07,2025-06-28,2578.0,0,0,3586,0,0,0

In [174]:
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                  377
median_time_between_txn_sec               377
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [175]:
# columns
time_cols = ['avg_time_between_txn_sec', 'median_time_between_txn_sec']

for col in time_cols:
    max_val = df7[col].max()
    df7[col] = df7[col].fillna(max_val)

df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                               377
max_txn_10min                             377
max_txn_1day                              377
max_txn_1week                             377
avg_txn_per_day                           377
avg_txn_per_hr                            377
avg_txn_per_week                          377
avg_txn_per_month                         377
night_txn_rate                            377
day_txn_rate                              377
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [176]:
burst_cols = [
    'max_txn_1hr',
    'max_txn_10min',
    'max_txn_1day',
    'max_txn_1week',
    'avg_txn_per_day',
    'avg_txn_per_hr',
    'avg_txn_per_week',
    'avg_txn_per_month',
    'night_txn_rate',
    'day_txn_rate'
]

df7[burst_cols] = df7[burst_cols].fillna(0)

In [177]:
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                 19395
unique_counterparty_count                 377
repeated_counterparty_frequency           377
unique_credit_counterparty_count          377
unique_debit_counterparty_count           377
avg_unique_counterparty_1hr               377
max_unique_counterparty_1hr               377
avg_repeated_counterparty_freq_1hr        377
avg_unique_counterparty_1day              377
max_unique_counterparty_1day              377
avg_repeated_counterparty_freq_1day       377
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

### counter party

In [178]:
counterparty_cols = [
    'unique_counterparty_count',
    'repeated_counterparty_frequency',
    'unique_credit_counterparty_count',
    'unique_debit_counterparty_count',
    'avg_unique_counterparty_1hr',
    'max_unique_counterparty_1hr',
    'avg_repeated_counterparty_freq_1hr',
    'avg_unique_counterparty_1day',
    'max_unique_counterparty_1day',
    'avg_repeated_counterparty_freq_1day'
]

df7[counterparty_cols] = df7[counterparty_cols].fillna(0)
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                 19395
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                             377
geo_frac                                  377
unique_geo_count                          377
geo_bbox_km                              3539
has_geo_flag                              377
ip_txn_count                              377
ip_frac                                   377
unique_ip_count                           377
top_ip_count                              768
top_ip_share                              768
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                        768
max_unique_ip_hour                        768
avg_unique_ip_day                         768
max_unique_ip_day                         768
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

geo

In [179]:
geo_ip_cols = [
    'geo_txn_count',
    'geo_frac',
    'unique_geo_count',
    'geo_bbox_km',
    'has_geo_flag',
    'ip_txn_count',
    'ip_frac',
    'unique_ip_count',
    'top_ip_count',
    'top_ip_share',
    'avg_unique_ip_hour',
    'max_unique_ip_hour',
    'avg_unique_ip_day',
    'max_unique_ip_day'
]

df7[geo_ip_cols] = df7[geo_ip_cols].fillna(0)
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                        405
credit_ratio                              377
debit_ratio                               377
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                 19395
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                            377
loan_ratio                                377
normal_ratio                              377
ci_ratio                                  377
bi_ratio                                  377
ip_ratio                                  377
ic_ratio                                  377
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

credit ratios

In [180]:
ratio_cols = [
    'credit_ratio',
    'debit_ratio',
    'credit_debit_ratio',
    'clt_cash_ratio',
    'loan_ratio',
    'normal_ratio',
    'ci_ratio',
    'bi_ratio',
    'ip_ratio',
    'ic_ratio'
]

df7[ratio_cols] = df7[ratio_cols].fillna(0)
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                 19395
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                         377
atm_deposit_frac                          377
atm_deposit_types                       11297
avg_balance_y                             377
min_balance                               377
avg_balance_credit                        396
avg_balance_debit                         405
max_balance                               377
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

deposite

In [181]:
cols_fill_zero = [
    'atm_deposit_count',
    'atm_deposit_frac',
    'avg_balance_y',
    'min_balance',
    'max_balance',
    'avg_balance_credit',
    'avg_balance_debit',
    'rapid_passthrough_count'
]

df7[cols_fill_zero] = df7[cols_fill_zero].fillna(0)  
df7.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                           377
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                       377
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                      377
least_common_mcc_code                     377
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                     0
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                           0
atm_deposit_frac                            0
atm_deposit_types                       11297
avg_balance_y                               0
min_balance                                 0
avg_balance_credit                          0
avg_balance_debit                           0
max_balance                                 0
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                     377
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [182]:
df8 = df7

In [183]:
# columns where NULL means no transactions
txn_cat_cols = [
    'most_common_mcc',
    'least_common_mcc_code',
    'most_common_channel',
    'least_common_channel'
]

df8[txn_cat_cols] = df8[txn_cat_cols].fillna('NO_TXN')


# ATM specific column
df8['atm_deposit_types'] = df8['atm_deposit_types'].fillna('NO_ATM')


# last transaction date
df8['last_transaction_date'] = df8['last_transaction_date'].fillna('NO_TXN')
df8.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                             0
max_mcc_frequency                         377
mcc_max_amount                            377
mcc_min_amount                            377
unique_channel_count                      377
most_common_channel                         0
max_channel_frequency                     377
channel_max_amount                        377
channel_min_amount                        377
avg_unique_mcc_per_hour                   377
avg_unique_mcc_per_day                    377
avg_unique_channel_per_hour               377
avg_unique_channel_per_day                377
least_common_channel                        0
least_common_mcc_code                       0
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                     0
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                           0
atm_deposit_frac                            0
atm_deposit_types                           0
avg_balance_y                               0
min_balance                                 0
avg_balance_credit                          0
avg_balance_debit                           0
max_balance                                 0
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                       0
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [184]:
# cols_fill_zero = [
#     'unique_mcc_count',
#     'max_mcc_frequency',
#     'mcc_max_amount',
#     'mcc_min_amount',
#     'unique_channel_count',
#     'max_channel_frequency',
#     'channel_max_amount',
#     'channel_min_amount',
#     'avg_unique_mcc_per_hour',
#     'avg_unique_mcc_per_day',
#     'avg_unique_channel_per_hour',
#     'avg_unique_channel_per_day'
# ]

# df8[cols_fill_zero] = df8[cols_fill_zero].fillna(0)
# df8.isnull().sum()

In [185]:
df9 = df8

In [186]:
MCC_CHANNEL_ZERO_FILL = [
    "max_mcc_frequency", "mcc_max_amount", "mcc_min_amount",
    "unique_channel_count", "max_channel_frequency",
    "channel_max_amount", "channel_min_amount",
    "avg_unique_mcc_per_hour", "avg_unique_mcc_per_day",
    "avg_unique_channel_per_hour", "avg_unique_channel_per_day",
]

for col in MCC_CHANNEL_ZERO_FILL:
    if col in df8.columns:
        df8[col] = df8[col].fillna(0)

In [187]:
df8.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                          377
most_common_mcc                             0
max_mcc_frequency                           0
mcc_max_amount                              0
mcc_min_amount                              0
unique_channel_count                        0
most_common_channel                         0
max_channel_frequency                       0
channel_max_amount                          0
channel_min_amount                          0
avg_unique_mcc_per_hour                     0
avg_unique_mcc_per_day                      0
avg_unique_channel_per_hour                 0
avg_unique_channel_per_day                  0
least_common_channel                        0
least_common_mcc_code                       0
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                     0
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                           0
atm_deposit_frac                            0
atm_deposit_types                           0
avg_balance_y                               0
min_balance                                 0
avg_balance_credit                          0
avg_balance_debit                           0
max_balance                                 0
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                       0
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [188]:
df8["unique_mcc_count"] = df8["unique_mcc_count"].fillna(0)

In [189]:
# cat_cols = [
#     'most_common_mcc',
#     'least_common_mcc_code',
#     'most_common_channel',
#     'least_common_channel',
#     'atm_deposit_types'
# ]

# df8[cat_cols] = df8[cat_cols].astype(str)

In [190]:
df8.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                            0
most_common_mcc                             0
max_mcc_frequency                           0
mcc_max_amount                              0
mcc_min_amount                              0
unique_channel_count                        0
most_common_channel                         0
max_channel_frequency                       0
channel_max_amount                          0
channel_min_amount                          0
avg_unique_mcc_per_hour                     0
avg_unique_mcc_per_day                      0
avg_unique_channel_per_hour                 0
avg_unique_channel_per_day                  0
least_common_channel                        0
least_common_mcc_code                       0
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                     0
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                           0
atm_deposit_frac                            0
atm_deposit_types                           0
avg_balance_y                               0
min_balance                                 0
avg_balance_credit                          0
avg_balance_debit                           0
max_balance                                 0
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                       0
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

In [191]:
df9 = df8

In [192]:
# df8.to_parquet("df_final.parquet", index=False)

In [193]:
object_cols = df8.select_dtypes(include="object").columns
object_cols

Index(['account_id', 'account_status', 'account_opening_date_x',
       'product_family', 'nomination_flag', 'cheque_allowed', 'cheque_availed',
       'last_mobile_update_date', 'kyc_compliant', 'last_kyc_date',
       'rural_branch', 'freeze_date', 'unfreeze_date', 'branch_address',
       'branch_city', 'branch_state', 'branch_type', 'scheme_code',
       'customer_id', 'date_of_birth', 'relationship_start_date',
       'pan_available', 'passport_available', 'mobile_banking_flag',
       'internet_banking_flag', 'atm_card_flag', 'demat_flag',
       'credit_card_flag', 'fastag_flag', 'name', 'gender',
       'address_last_update_date', 'address', 'phone_number',
       'passbook_last_update_date', 'joint_account_flag', 'nri_flag',
       'most_common_mcc', 'most_common_channel', 'channel_max_amount',
       'channel_min_amount', 'least_common_channel', 'least_common_mcc_code',
       'atm_deposit_types', 'account_opening_date_y', 'last_transaction_date'],
      dtype='object')

In [194]:
df9.sample(4)

,account_id,account_status,product_code,currency_code,account_opening_date_x,branch_code,branch_pin,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,last_mobile_update_date,kyc_compliant,last_kyc_date,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,freeze_date,unfreeze_date,branch_address,branch_pin_code,branch_city,branch_state,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,customer_id,multi_customer,date_of_birth,relationship_start_date,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,customer_pin,permanent_pin,name,gender,address_last_update_date,address,phone_number,passbook_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,account_opening_date_y,last_transaction_date,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag
111847,ACCT_139957,active,200,1,2023-01-29,6654,639010.0,53341.84,K,N,Y,N,0,None,Y,2024-08-02,N,49130.70,47291.76,53917.84,None,None,"75 Market Street, Shimla",201349,Shimla,Madhya Pradesh,36,13.40,492.31,semi-urban,PMJDY,CUST_139539,0,1952-12-20,1997-10-23,Y,-1.0,N,N,N,Y,N,N,N,639010,639010,Pranav Shah,M,2018-01-26,"374 Sector 45, Ranchi",91-9814003282,2021-03-11,N,N,-661472.54,3,0.0,0,0.0,0,53341.84,1,0.00,0,1273.0,50.0,9384.0,280.0,2557.0,2017.0,35.0,UPC,483.0,UPD,UPC,1.0,1.0,1.0,2.0,IAD,5941.0,91989831.02,72262.239607,42784000.00,-74115.68,1.285086e+06,833.74,71187728.45,20802102.57,42784000.00,9785000.00,3.422141,0.475255,0.524745,59714.572327,42472.5,3.0,2.0,6.0,17.0,1.446591,0.060332,10.103175,42.433333,0.048704,0.934014,4.0,21.0,0.983504,21.0,20.0,1.039248,3.0,0.000818,1.868182,6.0,0.019495,473.0,0.371563,473.0,15.034277,1.0,419.0,0.329144,419.0,1.0,0.002387,2.0,0.001571,CDM,3.830456e+07,-1289172.12,3.873132e+07,3.791805e+07,55264278.37,0.0,0.0,0.0,0.940299,0.036921,0.022781,0.0,1.0,2.0,1.0,4.0,0,2023-01-29,2025-06-28,881.0,0,0,9229,0,0,0
20820,ACCT_026083,active,100,1,2020-07-04,5975,190012.0,-44499.50,S,Y,Y,N,0,None,Y,2024-08-01,N,-47631.85,-49639.60,-31327.98,None,None,"165 Market Street, Patna",639007,Patna,Karnataka,49,8.15,351.76,urban,REGULAR,CUST_026009,0,1971-05-18,2002-06-07,N,-1.0,N,Y,Y,N,N,N,N,190012,411102,Sakshi Pandey,F,2023-08-23,"326 Sector 24, Jodhpur",91-9689208766,2025-01-05,N,N,0.00,0,0.0,0,0.0,0,0.00,0,-44499.50,1,1859.0,53.0,9384.0,358.0,4106.0,2557.0,32.0,UPC,653.0,IPM,P2A,1.0,1.0,1.0,1.0,IAD,7273.0,47265350.29,25425.148085,3763000.00,-100000.00,1.644290e+05,900.00,24498583.91,22766766.38,3763000.00,3391125.79,1.076068,0.470145,0.529855,84632.575350,61289.0,3.0,2.0,6.0,15.0,1.020868,0.042559,7.122605,30.983333,0.051641,0.929532,4.0,11.0,0.994083,11.0,10.0,1.032906,3.0,0.001952,1.555849,5.0,0.026620,503.0,0.270576,503.0,14.411387,1.0,640.0,0.344271,640.0,1.0,0.001563,5.0,0.002690,CDM,4.610670e+06,-715714.93,4.675714e+06,4.552956e+06,9967715.15,0.0,0.0,0.0,0.923077,0.045186,0.031737,0.0,1.0,2.0,1.0,4.0,0,2020-07-04,2025-06-28,1820.0,0,0,6602,0,0,0
82693,ACCT_103591,active,105,1,2023-11-11,3138,211021.0,4614.59,S,Y,Y,N,0,None,Y,2023-02-10,N,5378.11,3348.52,4966.10,None,None,"177 Industrial Area, Bangalore",831022,Bangalore,Goa,4,11.15,379.49,semi-urban,REGULAR,CUST_103282,0,2005-04-06,1996-01-23,Y,-1.0,Y,Y,N,N,Y,N,N,503014,503014,Advaith Pillai,M,2025-04-22,"460 Sector 28, Srinagar",91-6993728189,2022-05-08,N,N,-2487439.63,1,0.0,0,0.0,0,0.00,0,4614.59,1,2697.0,53.0,9384.0,606.0,2017.0,2557.0,34.0,UPC,1034.0,UPC,UPC,1.0,3.0,1.0,3.0,IAD,6012.0,70272874.67,26055.941665,27854820.98,-289000.00,5.432470e+05,1000.00,20180313.45,50092561.22,2639000.00,27854820.98,0.402860,0.473118,0.526882,19066.738131,10071.5,4.0,3.0,13.0,43.0,4.525168,0.188866,31.360465,134.850000,0.057471,0.923619,19.0,25.0,0.990730,25.0,24.0,1.138972,4.0,0.003258,4.189744,10.0,0.069985,698.0,0.258806,698.0,852.103673,1.0,907.0,0.336300,907.0,1.0,0.001103,10.0,0.003708,"CRM,CDM",-7.173338e+06,-31029463.59,-7.384907e+06,-6.983358e+06,2200080.02,0.0,0.0,0.0,0.959585,0.033370,0.007045,0.0,1.0,3.0,2.0,7.0,0,2023-11-11,2025-06-28,595.0,0,0,10154,0,0,0
1462,ACCT_001846,active,100,1,2023-03-23,7942,638025.0,0.00,S,Y,Y,N,0,2025-04-20,Y,2023-12-21,N,0.00,0.00,0.00,None,None,"31 Station Area, Varanasi",500135,Varanasi,Uttar Pradesh,20,8.72,159.76,urban,PMSBY,CUST_001839,0,1979-04-13,2008-07-24,Y,-1.0,Y,Y,Y,N,N,N,N,638025,638025,Kavya Shah,F,2022-09-06,"154 Nehru Road, Chennai",91-7971548826,None,N,N,0.00,0,0.0,0,0.0,0,0.00,0,0.00,1,3432.0,56.0,9384.0,714.0,5905.0,5905.0,35.0,UPC,1456.0,UPD,UPC,1.0,3.0,1.0,3.0,SCW,6012.0,98145263.46,28597.104738,9836813.29,-7853.41,2.500636e+05,1000.00,61584665.14,36560598.32,9836813.29,4524657.20,1.684455,0.486888,0.513112,20853.808511,10689.0,4.0,3.0,14.0,43.0,4.139928,0.172671,28.840336,122.571429,0.054487,0.923951,21.0,9.0,0.997378,9.0,8.0,1.099413,4.0,0.008991,3.307789,8.0,0.182665,929.0,0.270688,929.0,15.138830,1.0,1250.0,0.364219,1250.0,1.0,0.000800,8.0,0.002331,"CRM,CDM",8.570837e+06,-6672545.62,8.520577e+06,8.618528e+06,25005272.88,0.0,0.0,0.0,0.967657,0.024476,0.007867,0.0,1.0,3.0,2.0,7.0,-1,2023-03-23,2025-06-28,828.0,0,0,5355,0,0,0

In [195]:
df9.isnull().sum()

account_id                                  0
account_status                              0
product_code                                0
currency_code                               0
account_opening_date_x                      0
branch_code                                 0
branch_pin                              15505
avg_balance_x                               0
product_family                              0
nomination_flag                             0
cheque_allowed                              0
cheque_availed                              0
num_chequebooks                             0
last_mobile_update_date                135918
kyc_compliant                               0
last_kyc_date                               0
rural_branch                                0
monthly_avg_balance                         0
quarterly_avg_balance                       0
daily_avg_balance                           0
freeze_date                            148372
unfreeze_date                          156447
branch_address                              0
branch_pin_code                             0
branch_city                                 0
branch_state                                0
branch_employee_count                       0
branch_turnover                             0
branch_asset_size                           0
branch_type                                 0
scheme_code                                 0
customer_id                                 0
multi_customer                              0
date_of_birth                               0
relationship_start_date                     0
pan_available                               0
aadhaar_available                           0
passport_available                          0
mobile_banking_flag                         0
internet_banking_flag                       0
atm_card_flag                               0
demat_flag                                  0
credit_card_flag                            0
fastag_flag                                 0
customer_pin                                0
permanent_pin                               0
name                                        0
gender                                      0
address_last_update_date                    0
address                                     0
phone_number                                0
passbook_last_update_date               48106
joint_account_flag                          0
nri_flag                                    0
loan_sum                                    0
loan_count                                  0
cc_sum                                      0
cc_count                                    0
od_sum                                      0
od_count                                    0
ka_sum                                      0
ka_count                                    0
sa_sum                                      0
sa_count                                    0
total_transactions                          0
unique_mcc_count                            0
most_common_mcc                             0
max_mcc_frequency                           0
mcc_max_amount                              0
mcc_min_amount                              0
unique_channel_count                        0
most_common_channel                         0
max_channel_frequency                       0
channel_max_amount                          0
channel_min_amount                          0
avg_unique_mcc_per_hour                     0
avg_unique_mcc_per_day                      0
avg_unique_channel_per_hour                 0
avg_unique_channel_per_day                  0
least_common_channel                        0
least_common_mcc_code                       0
total_transaction_amount                    0
avg_transaction_amount                      0
max_transaction_amount                      0
min_transaction_amount                      0
std_transaction_amount                      0
median_transaction_amount                   0
total_credit_amount                         0
total_debit_amount                          0
max_credit_amount                           0
max_debit_amount                            0
credit_debit_ratio                          0
credit_ratio                                0
debit_ratio                                 0
avg_time_between_txn_sec                    0
median_time_between_txn_sec                 0
max_txn_1hr                                 0
max_txn_10min                               0
max_txn_1day                                0
max_txn_1week                               0
avg_txn_per_day                             0
avg_txn_per_hr                              0
avg_txn_per_week                            0
avg_txn_per_month                           0
night_txn_rate                              0
day_txn_rate                                0
rapid_passthrough_count                     0
unique_counterparty_count                   0
repeated_counterparty_frequency             0
unique_credit_counterparty_count            0
unique_debit_counterparty_count             0
avg_unique_counterparty_1hr                 0
max_unique_counterparty_1hr                 0
avg_repeated_counterparty_freq_1hr          0
avg_unique_counterparty_1day                0
max_unique_counterparty_1day                0
avg_repeated_counterparty_freq_1day         0
geo_txn_count                               0
geo_frac                                    0
unique_geo_count                            0
geo_bbox_km                                 0
has_geo_flag                                0
ip_txn_count                                0
ip_frac                                     0
unique_ip_count                             0
top_ip_count                                0
top_ip_share                                0
atm_deposit_count                           0
atm_deposit_frac                            0
atm_deposit_types                           0
avg_balance_y                               0
min_balance                                 0
avg_balance_credit                          0
avg_balance_debit                           0
max_balance                                 0
clt_cash_ratio                              0
loan_ratio                                  0
normal_ratio                                0
ci_ratio                                    0
bi_ratio                                    0
ip_ratio                                    0
ic_ratio                                    0
avg_unique_ip_hour                          0
max_unique_ip_hour                          0
avg_unique_ip_day                           0
max_unique_ip_day                           0
is_mule                                     0
account_opening_date_y                      0
last_transaction_date                       0
days_since_account_open                     0
account_open_issue_flag                     0
avg_balance_missing                         0
active_tenure_days                          0
monthly_avg_balance_missing                 0
account_frozen_flag                         0
zero_transaction_flag                       0
dtype: int64

product_code, account_opening_date_x,branch_code,branch_pin,last_mobile_update_date,last_kyc_date,freeze_date,unfreeze_date,branch_address,branch_pin_code ,branch_city,branch_state,customer_id,date_of_birth,relationship_start_date,customer_pin,permanent_pin,name,gender,passbook_last_update_date,phone_number,address,account_opening_date_y,last_transaction_date

In [196]:
cols_to_drop = [
    "product_code",
    "account_opening_date_x",
    "branch_code",
    "branch_pin",
    "last_mobile_update_date",
    "last_kyc_date",
    "freeze_date",
    "unfreeze_date",
    "branch_address",
    "branch_pin_code",
    "branch_city",
    "branch_state",
    "customer_id",
    "date_of_birth",
    "relationship_start_date",
    "customer_pin",
    "permanent_pin",
    "name",
    "gender",
    "passbook_last_update_date",
    "phone_number",
    "address",
    "account_opening_date_y",
    "last_transaction_date"
]

df9 = df9.drop(columns=cols_to_drop, errors="ignore")
print(df8.shape)
print(df9.shape)
df9.sample(3)

(160153, 156)
(160153, 132)

,account_id,account_status,currency_code,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,kyc_compliant,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,multi_customer,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,address_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,channel_max_amount,channel_min_amount,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag
151869,ACCT_189764,active,1,-22138.47,K,Y,Y,N,0,Y,N,-18044.410,-27154.68,-22217.72,42,20.74,391.03,semi-urban,REGULAR,0,Y,-1.0,N,N,N,Y,N,N,N,2018-04-02,Y,N,0.00,0,0.00,0,0.0,0,-22138.47,1,0.00,0,1440.0,50.0,9384.0,315.0,2557.0,5905.0,31.0,UPC,581.0,UPC,UPD,1.0,1.0,1.0,1.0,IAD,6011.0,31932140.94,22175.097875,3797000.00,-31048.2,137320.056778,893.64,20094805.64,11837335.30,3797000.0,1348600.00,1.697578,0.479167,0.520833,109096.351633,76987.0,2.0,2.0,6.0,13.0,0.792079,0.033020,5.538462,24.000000,0.059722,0.924306,0.0,5.0,0.996528,5.0,4.0,1.014904,2.0,0.003549,1.337067,4.0,0.050900,584.0,0.405556,584.0,2237.913931,1.0,517.0,0.359028,517.0,1.0,0.001934,0.0,0.000000,NO_ATM,2.172866e+06,-610857.84,2.208005e+06,2.140539e+06,8236172.39,0.0,0.0,0.0,0.924306,0.034028,0.041667,0.0,1.0,2.0,1.0,3.0,-1,2132.0,0,0,233,0,0,0
34965,ACCT_043728,active,1,4551.00,S,Y,Y,N,0,N,N,4518.235,480.70,237.27,20,14.63,392.44,urban,REGULAR,0,Y,-1.0,N,N,N,Y,N,N,N,2024-03-18,N,N,0.00,0,0.00,0,0.0,0,0.00,0,387.94,1,907.0,44.0,9384.0,196.0,2920.0,5192.0,30.0,UPD,315.0,P2A,UPC,1.0,1.0,1.0,1.0,STC,7399.0,34153020.10,37654.928445,13011676.47,-1500.0,465655.065713,1000.00,14309059.02,19843961.08,3884900.0,13011676.47,0.721079,0.478501,0.521499,137134.133554,93370.5,2.0,2.0,4.0,11.0,0.630299,0.026279,4.402913,18.895833,0.052922,0.932745,1.0,16.0,0.982359,16.0,15.0,1.016816,2.0,0.000000,1.312224,4.0,0.010309,308.0,0.339581,308.0,15.439132,1.0,305.0,0.336273,305.0,1.0,0.003279,5.0,0.005513,"CDM,CRM",-6.061495e+06,-8610105.50,-5.931361e+06,-6.180899e+06,4952611.15,0.0,0.0,0.0,0.918412,0.029768,0.051819,0.0,1.0,2.0,1.0,4.0,0,1443.0,0,1,5036,1,0,0
46894,ACCT_058644,active,1,1657.00,S,N,Y,Y,2,Y,N,1420.040,1877.74,1487.38,41,16.01,259.99,urban,REGULAR,0,Y,-1.0,N,Y,N,N,N,Y,N,2024-08-01,N,N,-360974.07,2,-129735.59,1,0.0,0,0.00,0,1657.00,1,3382.0,57.0,9384.0,669.0,2199.0,5905.0,35.0,UPC,1258.0,NWD,UPD,1.0,4.0,1.0,4.0,SCW,5251.0,77697689.06,22973.887954,6947977.85,-360000.0,169366.887247,1000.00,27994220.45,49703468.61,2378300.0,6947977.85,0.563225,0.460970,0.539030,12322.674357,5984.0,5.0,3.0,21.0,61.0,7.002070,0.292207,49.014493,211.375000,0.055884,0.928149,34.0,29.0,0.991425,29.0,28.0,1.212812,5.0,0.004627,6.258333,15.0,0.092904,904.0,0.267297,904.0,15.050128,1.0,1217.0,0.359846,1217.0,1.0,0.000822,9.0,0.002661,"CRM,CDM",-9.281491e+06,-23857945.94,-9.064564e+06,-9.467003e+06,486503.49,0.0,0.0,0.0,0.958604,0.036960,0.004435,0.0,1.0,3.0,3.0,9.0,0,482.0,0,0,1194,0,0,0

In [197]:
df9.isnull().sum()

account_id                             0
account_status                         0
currency_code                          0
avg_balance_x                          0
product_family                         0
nomination_flag                        0
cheque_allowed                         0
cheque_availed                         0
num_chequebooks                        0
kyc_compliant                          0
rural_branch                           0
monthly_avg_balance                    0
quarterly_avg_balance                  0
daily_avg_balance                      0
branch_employee_count                  0
branch_turnover                        0
branch_asset_size                      0
branch_type                            0
scheme_code                            0
multi_customer                         0
pan_available                          0
aadhaar_available                      0
passport_available                     0
mobile_banking_flag                    0
internet_banking_flag                  0
atm_card_flag                          0
demat_flag                             0
credit_card_flag                       0
fastag_flag                            0
address_last_update_date               0
joint_account_flag                     0
nri_flag                               0
loan_sum                               0
loan_count                             0
cc_sum                                 0
cc_count                               0
od_sum                                 0
od_count                               0
ka_sum                                 0
ka_count                               0
sa_sum                                 0
sa_count                               0
total_transactions                     0
unique_mcc_count                       0
most_common_mcc                        0
max_mcc_frequency                      0
mcc_max_amount                         0
mcc_min_amount                         0
unique_channel_count                   0
most_common_channel                    0
max_channel_frequency                  0
channel_max_amount                     0
channel_min_amount                     0
avg_unique_mcc_per_hour                0
avg_unique_mcc_per_day                 0
avg_unique_channel_per_hour            0
avg_unique_channel_per_day             0
least_common_channel                   0
least_common_mcc_code                  0
total_transaction_amount               0
avg_transaction_amount                 0
max_transaction_amount                 0
min_transaction_amount                 0
std_transaction_amount                 0
median_transaction_amount              0
total_credit_amount                    0
total_debit_amount                     0
max_credit_amount                      0
max_debit_amount                       0
credit_debit_ratio                     0
credit_ratio                           0
debit_ratio                            0
avg_time_between_txn_sec               0
median_time_between_txn_sec            0
max_txn_1hr                            0
max_txn_10min                          0
max_txn_1day                           0
max_txn_1week                          0
avg_txn_per_day                        0
avg_txn_per_hr                         0
avg_txn_per_week                       0
avg_txn_per_month                      0
night_txn_rate                         0
day_txn_rate                           0
rapid_passthrough_count                0
unique_counterparty_count              0
repeated_counterparty_frequency        0
unique_credit_counterparty_count       0
unique_debit_counterparty_count        0
avg_unique_counterparty_1hr            0
max_unique_counterparty_1hr            0
avg_repeated_counterparty_freq_1hr     0
avg_unique_counterparty_1day           0
max_unique_counterparty_1day           0
avg_repeated_counterparty_freq_1day    0
geo_txn_count                          0
geo_frac                               0
unique_geo_count                       0
geo_bbox_km                            0
has_geo_flag                           0
ip_txn_count                           0
ip_frac                                0
unique_ip_count                        0
top_ip_count                           0
top_ip_share                           0
atm_deposit_count                      0
atm_deposit_frac                       0
atm_deposit_types                      0
avg_balance_y                          0
min_balance                            0
avg_balance_credit                     0
avg_balance_debit                      0
max_balance                            0
clt_cash_ratio                         0
loan_ratio                             0
normal_ratio                           0
ci_ratio                               0
bi_ratio                               0
ip_ratio                               0
ic_ratio                               0
avg_unique_ip_hour                     0
max_unique_ip_hour                     0
avg_unique_ip_day                      0
max_unique_ip_day                      0
is_mule                                0
days_since_account_open                0
account_open_issue_flag                0
avg_balance_missing                    0
active_tenure_days                     0
monthly_avg_balance_missing            0
account_frozen_flag                    0
zero_transaction_flag                  0
dtype: int64

In [198]:
# Find every object column that still has float values hiding inside
problem_cols = []
for col in df9.select_dtypes(include="object").columns:
    has_float = df9[col].apply(lambda x: isinstance(x, float)).any()
    if has_float:
        problem_cols.append(col)

print("Columns with mixed float/string:", problem_cols)

Columns with mixed float/string: ['most_common_mcc', 'least_common_mcc_code']

In [199]:
# These two still have float NaN hiding inside despite fillna
for col in ['most_common_mcc', 'least_common_mcc_code']:
    df9[col] = df9[col].astype(str)
    df9[col] = df9[col].replace({"nan": "NO_TXN", "None": "NO_TXN"})

# Verify
for col in ['most_common_mcc', 'least_common_mcc_code']:
    has_float = df9[col].apply(lambda x: isinstance(x, float)).any()
    print(f"{col} — float remaining: {has_float}")
    print(f"  unique sample: {df9[col].unique()[:5]}")

most_common_mcc — float remaining: False
  unique sample: ['NO_TXN' '9384.0' '5411.0' '2017.0' '5682.0']
least_common_mcc_code — float remaining: False
  unique sample: ['NO_TXN' '9355.0' '5812.0' '9256.0' '2769.0']

In [200]:
def clean_mcc_code(val):
    if val == "NO_TXN":
        return val
    try:
        return str(int(float(val)))  # "9384.0" → 9384 → "9384"
    except:
        return "NO_TXN"

df9["most_common_mcc"]      = df9["most_common_mcc"].apply(clean_mcc_code)
df9["least_common_mcc_code"] = df9["least_common_mcc_code"].apply(clean_mcc_code)

# Verify
print(df9["most_common_mcc"].unique()[:5])
# Should show: ['NO_TXN' '9384' '5411' '2017' '5682']

['NO_TXN' '9384' '5411' '2017' '5682']

In [201]:
df9.shape

(160153, 132)

In [202]:
# See all non-numeric values in this column
non_numeric = df9["channel_max_amount"].apply(
    lambda x: x if isinstance(x, str) else None
).dropna().unique()

print("Non-numeric values found:")
print(non_numeric)
print(f"\nTotal non-numeric rows: {df9['channel_max_amount'].apply(lambda x: isinstance(x, str)).sum()}")

Non-numeric values found:
['UPD' 'END' 'FTC' 'UPC' 'TPC' 'FTD' 'NTD' 'CHQ' 'IPM' 'TPD' 'MAC' 'ETD'
 'IFD' 'PCA' 'STD' 'RCD' 'NWD' 'IFC' 'CCL' 'CSD' 'ATW' 'P2A' 'MCR' 'STC'
 'OCD' 'CHD' 'MAD' 'CTC' 'ASD' 'APD' 'RTD' 'OPI' 'SCW' 'SID' 'IAD']

Total non-numeric rows: 159776

In [203]:
df9.shape

(160153, 132)

In [204]:
# Check if channel_min_amount has the same problem
print(df9["channel_min_amount"].dtype)
print(df9["channel_min_amount"].unique()[:10])

# Check all amount columns for the same corruption
amount_cols = [c for c in df9.columns if "amount" in c.lower()]
for col in amount_cols:
    sample = df9[col].unique()[:5]
    print(f"{col}: {sample}")

object
[0 'UPC' 'UPD' 'IPM' 'P2A' 'FTC' 'APD' 'FTD' 'OCD' 'NTD']
mcc_max_amount: [   0. 5651. 5311. 3478. 4784.]
mcc_min_amount: [   0. 9355. 5812. 3478. 4121.]
channel_max_amount: [0 'UPD' 'END' 'FTC' 'UPC']
channel_min_amount: [0 'UPC' 'UPD' 'IPM' 'P2A']
total_transaction_amount: [      0.     55249.28 6214812.87  954705.32 1049165.14]
avg_transaction_amount: [    0.          3453.08       62148.1287     31823.51066667
 30857.79823529]
max_transaction_amount: [     0.    16337.44 348937.23  79714.65  50000.  ]
min_transaction_amount: [   0.     16.38 1792.49 1772.18 1052.93]
std_transaction_amount: [    0.          4675.46278802 62913.22803537 20013.28055385
 17771.41894824]
median_transaction_amount: [    0.     410.73 38877.6  45147.   35199.  ]
total_credit_amount: [      0.     23070.25 2929468.92  278459.57  710248.75]
total_debit_amount: [      0.     32179.03 3285343.95  676245.75  338916.39]
max_credit_amount: [     0.     8381.72 348937.23  49749.    50000.  ]
max_debit_amount: [     0.    16337.44 325069.75  79714.65  50000.  ]

In [205]:
df9 = df9.drop(columns=["channel_max_amount", "channel_min_amount"])
df9.shape

(160153, 130)

In [206]:
# df9.to_parquet("df_final.parquet", index=False)

In [207]:
df = pd.read_parquet("df_final.parquet")
print(df.shape) 
df9.sample(7)

(160153, 130)

,account_id,account_status,currency_code,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,kyc_compliant,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,multi_customer,pan_available,aadhaar_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,address_last_update_date,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,most_common_channel,max_channel_frequency,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_channel,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,atm_deposit_types,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag
19751,ACCT_024752,active,1,7455.05,S,Y,Y,N,0,Y,N,7846.870,5724.18,4197.75,11,22.62,297.15,urban,PMSBY,0,N,-1.0,N,N,Y,Y,N,N,N,2020-11-25,N,N,0.00,0,0.0,0,0.0,0,0.00,0,7455.05,1,1894.0,56.0,9384,414.0,5905.0,5682.0,33.0,UPC,688.0,1.0,1.0,1.0,1.0,CTC,6012,4.027486e+07,21264.444773,2164000.00,-9000.00,109459.950923,1000.0,18493182.85,21781675.55,2164000.00,1871000.0,0.849025,0.468849,0.531151,83200.122557,63078.0,3.0,2.0,6.0,16.0,1.038377,0.043290,7.256705,31.566667,0.055966,0.930834,1.0,20.0,0.989440,20.0,19.0,1.027732,3.0,0.001088,1.565365,6.0,0.015054,673.0,0.355333,673.0,15.498896,1.0,663.0,0.350053,663.0,1.0,0.001508,5.0,0.002640,"CDM,CRM",-3.372716e+06,-7182495.88,-3.365679e+06,-3.378927e+06,607263.67,0.0,0.0,0.0,0.933474,0.034847,0.031679,0.0,1.0,2.0,1.0,4.0,-1,1982.0,0,0,841,0,0,0
98939,ACCT_123896,active,1,27868.68,K,N,Y,N,0,Y,N,32808.130,22344.63,34517.16,14,22.24,473.56,semi-urban,PMSBY,0,Y,-1.0,N,Y,Y,Y,N,N,N,2019-09-30,N,Y,-840808.67,2,0.0,0,0.0,0,27868.68,1,0.00,0,1684.0,56.0,9384,349.0,5905.0,9355.0,34.0,UPC,616.0,1.0,3.0,1.0,3.0,ASD,6051,4.233894e+07,25141.888860,4841572.27,-69500.00,186567.331223,1000.0,20494923.89,21844016.95,4841572.27,4123013.2,0.938240,0.473872,0.526128,19758.503268,10222.0,3.0,2.0,14.0,46.0,4.362694,0.182271,30.071429,129.538462,0.051069,0.927553,5.0,46.0,0.972684,12.0,44.0,1.131741,3.0,0.008305,3.583554,8.0,0.150595,643.0,0.381829,643.0,14.627357,1.0,564.0,0.334917,564.0,1.0,0.001773,6.0,0.003563,"CDM,CRM",-2.452871e+06,-7446220.90,-2.589933e+06,-2.329423e+06,931805.33,0.0,0.0,0.0,0.959620,0.033254,0.007126,0.0,1.0,3.0,2.0,8.0,-1,385.0,0,0,4665,0,0,0
150916,ACCT_188570,active,1,9565.68,S,Y,Y,Y,0,Y,N,10626.840,7397.71,12794.14,49,12.47,132.21,urban,REGULAR,0,N,-1.0,N,N,N,N,N,N,N,2023-10-12,N,N,0.00,0,0.0,0,0.0,0,0.00,0,9565.68,1,3477.0,56.0,9384,728.0,2920.0,2944.0,34.0,UPC,1311.0,1.0,4.0,1.0,3.0,SCW,5941,1.043036e+08,29998.169129,5752500.00,-1487711.46,225025.404173,1000.0,38122660.81,66180973.25,4223638.85,5752500.0,0.576037,0.466782,0.533218,13669.771289,6866.5,4.0,4.0,17.0,64.0,6.310345,0.263409,44.012658,183.000000,0.057233,0.925223,26.0,25.0,0.992810,25.0,24.0,1.192613,4.0,0.003567,5.617375,13.0,0.100971,1447.0,0.416163,1447.0,15.013254,1.0,1203.0,0.345988,1203.0,1.0,0.000831,11.0,0.003164,"CRM,CDM",-2.164497e+07,-34618459.97,-2.146636e+07,-2.180133e+07,245675.40,0.0,0.0,0.0,0.955134,0.039689,0.005177,0.0,1.0,3.0,3.0,7.0,0,550.0,0,0,9378,0,0,0
3980,ACCT_005027,active,1,7114.91,S,N,Y,N,0,Y,N,6090.480,8461.58,4810.24,6,11.06,338.86,rural,REGULAR,0,Y,-1.0,Y,N,Y,Y,N,N,N,2017-09-06,N,N,0.00,0,0.0,0,0.0,0,0.00,0,7114.91,1,1870.0,51.0,9384,392.0,5905.0,2955.0,35.0,UPD,693.0,1.0,4.0,1.0,3.0,IAD,6211,4.564624e+07,24409.754198,6414200.00,-19233.47,213798.837229,1000.0,24687349.21,20958891.14,6414200.00,3705164.6,1.177894,0.465775,0.534225,14118.448368,7140.0,5.0,2.0,16.0,68.0,6.111111,0.255081,42.500000,170.000000,0.066310,0.911230,18.0,12.0,0.993583,12.0,11.0,1.182168,4.0,0.007772,4.752542,10.0,0.205673,642.0,0.343316,642.0,1542.093241,1.0,632.0,0.337968,632.0,1.0,0.001582,6.0,0.003209,CDM,5.278907e+06,-60169.32,5.322870e+06,5.240578e+06,8333823.48,0.0,0.0,0.0,0.957754,0.036898,0.005348,0.0,1.0,4.0,2.0,8.0,0,305.0,0,0,7434,0,0,0
114862,ACCT_143719,active,1,223.01,S,Y,Y,Y,2,Y,N,211.580,246.96,264.41,25,5.90,250.54,semi-urban,REGULAR,0,N,-1.0,N,N,N,N,N,N,N,2017-06-22,N,N,0.00,0,0.0,0,0.0,0,0.00,0,223.01,1,951.0,41.0,9384,186.0,2557.0,9355.0,31.0,UPC,352.0,1.0,1.0,1.0,1.0,ASD,7273,2.195545e+07,23086.699506,4459000.00,-2000.00,167218.589008,1000.0,9560955.73,12394495.50,4459000.00,1353800.0,0.771387,0.474238,0.525762,110992.146316,76934.0,2.0,2.0,5.0,13.0,0.778870,0.032467,5.434286,23.195122,0.051525,0.929548,1.0,23.0,0.975815,23.0,22.0,1.035948,2.0,0.000000,1.437596,5.0,0.010837,294.0,0.309148,294.0,15.157543,1.0,361.0,0.379600,361.0,1.0,0.002770,4.0,0.004206,"CDM,CRM",-1.587794e+06,-4508835.17,-1.584483e+06,-1.590781e+06,734302.05,0.0,0.0,0.0,0.933754,0.024185,0.042061,0.0,1.0,2.0,1.0,3.0,0,1220.0,0,0,7827,0,0,0
144754,ACCT_180911,active,1,4551.00,S,N,Y,N,0,Y,N,4518.235,5438.57,6565.25,47,8.35,112.66,semi-urban,REGULAR,0,Y,-1.0,Y,N,Y,Y,N,N,N,2020-06-27,N,N,0.00,0,0.0,0,0.0,0,0.00,0,4380.70,1,3037.0,55.0,9384,674.0,5905.0,2769.0,35.0,UPC,1318.0,1.0,2.0,1.0,2.0,CCL,5251,7.332286e+07,24143.187109,6498000.00,-78700.00,177692.263149,1000.0,36236459.65,37086399.60,4023700.00,6498000.0,0.977082,0.466908,0.533092,26880.252635,13911.0,4.0,2.0,11.0,34.0,3.213757,0.133966,22.496296,94.906250,0.053342,0.927889,9.0,14.0,0.995390,14.0,13.0,1.095602,4.0,0.003787,3.008929,8.0,0.078864,886.0,0.291735,886.0,586.491701,1.0,1059.0,0.348699,1059.0,1.0,0.000944,2.0,0.000659,CRM,-2.013754e+06,-7171569.99,-2.008653e+06,-2.018221e+06,1250805.26,0.0,0.0,0.0,0.960487,0.029305,0.010207,0.0,1.0,3.0,2.0,7.0,-1,944.0,0,1,3964,1,0,0
146182,ACCT_182686,active,1,60670.96,S,Y,Y,N,0,Y,N,59926.430,47566.71,80902.32,14,13.08,188.51,semi-urban,REGULAR,0,N,-1.0,N,N,N,Y,N,N,N,2023-11-19,N,N,0.00,0,0.0,0,0.0,0,0.00,0,60670.96,1,1051.0,50.0,9384,251.0,2769.0,5905.0,30.0,UPC,388.0,1.0,3.0,1.0,3.0,MAD,5944,2.312051e+07,21998.581598,1775000.00,-25443.14,107697.178844,1000.0,12925155.47,10195353.79,1775000.00,1213071.5,1.267750,0.450999,0.549001,22331.235238,11111.5,4.0,2.0,12.0,38.0,3.863971,0.161345,26.948718,105.100000,0.068506,0.918173,5.0,22.0,0.979068,22.0,21.0,1.123391,4.0,0.001967,3.722008,9.0,0.061436,274.0,0.260704,274.0,14.856762,1.0,383.0,0.364415,383.0,1.0,0.002611,4.0,0.003806,"CRM,CDM",1.732352e+06,-353805.63,1.707965e+06,1.752385e+06,3283546.89,0.0,0.0,0.0,0.959087,0.032350,0.008563,0.0,1.0,3.0,2.0,6.0,0,271.0,0,0,10303,0,0,0

In [208]:
df9.isnull().sum()

account_id                             0
account_status                         0
currency_code                          0
avg_balance_x                          0
product_family                         0
nomination_flag                        0
cheque_allowed                         0
cheque_availed                         0
num_chequebooks                        0
kyc_compliant                          0
rural_branch                           0
monthly_avg_balance                    0
quarterly_avg_balance                  0
daily_avg_balance                      0
branch_employee_count                  0
branch_turnover                        0
branch_asset_size                      0
branch_type                            0
scheme_code                            0
multi_customer                         0
pan_available                          0
aadhaar_available                      0
passport_available                     0
mobile_banking_flag                    0
internet_banking_flag                  0
atm_card_flag                          0
demat_flag                             0
credit_card_flag                       0
fastag_flag                            0
address_last_update_date               0
joint_account_flag                     0
nri_flag                               0
loan_sum                               0
loan_count                             0
cc_sum                                 0
cc_count                               0
od_sum                                 0
od_count                               0
ka_sum                                 0
ka_count                               0
sa_sum                                 0
sa_count                               0
total_transactions                     0
unique_mcc_count                       0
most_common_mcc                        0
max_mcc_frequency                      0
mcc_max_amount                         0
mcc_min_amount                         0
unique_channel_count                   0
most_common_channel                    0
max_channel_frequency                  0
avg_unique_mcc_per_hour                0
avg_unique_mcc_per_day                 0
avg_unique_channel_per_hour            0
avg_unique_channel_per_day             0
least_common_channel                   0
least_common_mcc_code                  0
total_transaction_amount               0
avg_transaction_amount                 0
max_transaction_amount                 0
min_transaction_amount                 0
std_transaction_amount                 0
median_transaction_amount              0
total_credit_amount                    0
total_debit_amount                     0
max_credit_amount                      0
max_debit_amount                       0
credit_debit_ratio                     0
credit_ratio                           0
debit_ratio                            0
avg_time_between_txn_sec               0
median_time_between_txn_sec            0
max_txn_1hr                            0
max_txn_10min                          0
max_txn_1day                           0
max_txn_1week                          0
avg_txn_per_day                        0
avg_txn_per_hr                         0
avg_txn_per_week                       0
avg_txn_per_month                      0
night_txn_rate                         0
day_txn_rate                           0
rapid_passthrough_count                0
unique_counterparty_count              0
repeated_counterparty_frequency        0
unique_credit_counterparty_count       0
unique_debit_counterparty_count        0
avg_unique_counterparty_1hr            0
max_unique_counterparty_1hr            0
avg_repeated_counterparty_freq_1hr     0
avg_unique_counterparty_1day           0
max_unique_counterparty_1day           0
avg_repeated_counterparty_freq_1day    0
geo_txn_count                          0
geo_frac                               0
unique_geo_count                       0
geo_bbox_km                            0
has_geo_flag                           0
ip_txn_count                           0
ip_frac                                0
unique_ip_count                        0
top_ip_count                           0
top_ip_share                           0
atm_deposit_count                      0
atm_deposit_frac                       0
atm_deposit_types                      0
avg_balance_y                          0
min_balance                            0
avg_balance_credit                     0
avg_balance_debit                      0
max_balance                            0
clt_cash_ratio                         0
loan_ratio                             0
normal_ratio                           0
ci_ratio                               0
bi_ratio                               0
ip_ratio                               0
ic_ratio                               0
avg_unique_ip_hour                     0
max_unique_ip_hour                     0
avg_unique_ip_day                      0
max_unique_ip_day                      0
is_mule                                0
days_since_account_open                0
account_open_issue_flag                0
avg_balance_missing                    0
active_tenure_days                     0
monthly_avg_balance_missing            0
account_frozen_flag                    0
zero_transaction_flag                  0
dtype: int64